"use client"
import { createContext, useState, useContext, useEffect } from "react"

// Available languages
const languages = {
    uz: "O'zbek",
    ru: "Русский",
    en: "English",
}

// Translations
const translations = {
    uz: {
        // Auth
        login: "Kirish",
        signup: "Ro'yxatdan o'tish",
        logout: "Chiqish",
        email: "Email",
        password: "Parol",
        confirm_password: "Parolni tasdiqlang",
        forgot_password: "Parolni unutdingizmi?",
        remember_me: "Meni eslab qol",
        request_access: "Kirish huquqini so'rash",
        loggingIn: "Kirish...",
        or: "yoki",
        noAccount: "Hisobingiz yo'qmi?",
        signUp: "Ro'yxatdan o'ting",
        requestReceived: "So'rovingiz qabul qilindi",
        credentialsSentTo: "Login va parol ma'lumotlari quyidagi elektron pochtaga yuboriladi:",
        backToLogin: "Loginni qaytish",
        loginInstructions: "Tizimga kirish uchun ma'lumotlaringizni kiriting",
        emailPasswordRequired: "Email va parol kiritilishi shart",
        loginFailed: "Kirish muvaffaqiyatsiz bo'ldi",
        clinicName: "Klinika nomi",
        enterClinicInfo: "Klinika ma'lumotlarini kiriting",
        submit: "Yuborish",
        back: "Orqaga",

        // Roles
        director: "Direktor",
        admin: "Administrator",
        doctor: "Shifokor",
        user: "Foydalanuvchi",
        nurse: "Hamshira",

        // Dashboard
        dashboard: "Dashboard",
        staff: "Xodimlar",
        tasks: "Vazifalar",
        cabinets: "Kabinetlar",
        inpatient_rooms: "Statsionar xonalar",
        patients: "Bemorlar",
        appointments: "Qabullar",
        reports: "Hisobotlar",
        settings: "Sozlamalar",
        notifications: "Xabarnomalar",
        profile: "Profil",
        loading: "Yuklanmoqda",
        allBranches: "Barcha filiallar",

        // Main Menu
        main_menu: "Asosiy menyu",
        home: "Bosh sahifa",
        account: "Hisob",
        help: "Yordam",
        help_center: "Yordam markazi",

        // Patient Care
        patient_care: "Bemor parvarishi",
        vital_signs: "Hayotiy ko'rsatkichlar",
        medications: "Dori-darmonlar",

        // Additional terms
        finance: "Moliya",
        all_staff: "Barcha xodimlar",
        doctors: "Shifokorlar",
        nurses: "Hamshiralar",
        all_rights_reserved: "Barcha huquqlar himoyalangan",
        privacy_policy: "Maxfiylik siyosati",
        terms_of_service: "Xizmat ko'rsatish shartlari",
        minutesAgo: "daqiqa oldin",
        hoursAgo: "soat oldin",
        new_patient_added: "Yangi bemor qo'shildi",
        appointment_reminder: "Qabul eslatmasi",
        system_updated: "Tizim yangilandi",
        room_maintenance_completed: "Xona ta'mirlash ishlari tugadi",
        patients_today: "Bugungi bemorlar",
        appointments_today: "Bugungi qabullar",
        error_occurred: "Xatolik yuz berdi",
        try_again: "Qayta urinib ko'rish",

        // Common
        search: "Qidirish...",
        filters: "Filtrlar",
        all: "Barchasi",
        active: "Faol",
        inactive: "Nofaol",
        add: "Qo'shish",
        save: "Saqlash",
        cancel: "Bekor qilish",
        edit: "Tahrirlash",
        delete: "O'chirish",
        actions: "Amallar",
        name: "Ism",
        status: "Holat",
        branch: "Filial",
        branch1: "1-Filial",
        branch2: "2-Filial",
        branch3: "3-Filial",
        no_data_found: "Ma'lumot topilmadi",
        statistics: "Statistika",
        close_stats: "Statistikani yopish",
        today: "Bugun",
        yesterday: "Kecha",
        daysAgo: "kun oldin",
        markAllAsRead: "Hammasini o'qilgan deb belgilash",
        markAsRead: "O'qilgan deb belgilash",
        read: "O'qilgan",
        unread: "O'qilmagan",
        siteNews: "Sayt yangiliklari",
        workNotifications: "Ish xabarlari",
        noNotifications: "Xabarnomalar yo'q",
        high: "Yuqori",
        medium: "O'rta",
        low: "Past",
        priority: "Muhimlik",
        settingsSaved: "Sozlamalar saqlandi",
        guest: "Mehmon",

        // Staff
        add_new_staff: "Yangi xodim qo'shish",
        edit_staff: "Xodimni tahrirlash",
        confirm_delete_staff: "Rostdan ham bu xodimni o'chirmoqchimisiz?",
        position: "Lavozim",
        department: "Bo'lim",
        phone: "Telefon",
        monthly_salary: "Oylik maosh",
        vacation_status: "Ta'til holati",
        on_vacation: "Ta'tilda",
        at_work: "Ishda",
        vacation_period: "Ta'til muddati",
        vacation_period_example: "Misol: 2023-05-20 - 2023-06-05",
        full_name: "To'liq ism",
        total_staff: "Jami xodimlar",
        active_staff: "Faol xodimlar",
        staff_on_vacation: "Ta'tildagi xodimlar",
        total_salary: "Jami oylik maosh",
        role_distribution: "Lavozimlar bo'yicha taqsimot",
        currency: "so'm",
        inactive_staff: "Nofaol xodimlar",

        // Staff positions
        doctor: "Shifokor",
        admin: "Administrator",
        nurse: "Hamshira",
        lab_technician: "Laborant",
        pharmacist: "Farmatsevt",
        receptionist: "Qabulxona xodimi",
        accountant: "Hisobchi",
        cleaner: "Tozalovchi",
        security: "Qo'riqchi",
        buyer: "Xarid bo'yicha mutaxassis",
        manager: "Menejer",

        // Cabinets
        add_new_cabinet: "Yangi kabinet qo'shish",
        edit_cabinet: "Kabinetni tahrirlash",
        confirm_delete_cabinet: "Rostdan ham bu kabinetni o'chirmoqchimisiz?",
        cabinet_number: "Kabinet raqami",
        cabinet_name: "Kabinet nomi",
        floor: "Qavat",
        capacity: "Sig'imi",
        doctors_count: "shifokorlar soni",
        maintenance: "Ta'mirda",
        total_cabinets: "Jami kabinetlar",
        active_cabinets: "Faol kabinetlar",
        maintenance_cabinets: "Ta'mirdagi kabinetlar",
        total_capacity: "Jami sig'im",
        floor_distribution: "Qavatlar bo'yicha taqsimot",
        number: "Raqam",
        inactive_cabinets: "Nofaol kabinetlar",
        examination: "Tekshiruv",
        procedure: "Protsedura",
        surgery: "Jarrohlik",
        laboratory: "Laboratoriya",
        x_ray: "Rentgen",
        type: "Turi",
        equipment: "Jihozlar",
        type_distribution: "Tur bo'yicha taqsimot",
        available: "Mavjud",
        occupied: "Band",
        cabinets_management: "Kabinetlar boshqaruvi",
        search_cabinets: "Kabinetlarni qidirish",
        all_types: "Barcha turlar",
        examination_room: "Tekshiruv xonasi",
        procedure_room: "Protsedura xonasi",
        surgery_room: "Jarrohlik xonasi",
        laboratory: "Laboratoriya",
        dental_room: "Stomatologiya xonasi",
        all_branches: "Barcha filiallar",
        available_cabinets: "Mavjud kabinetlar",
        occupied_cabinets: "Band kabinetlar",
        maintenance_cabinets: "Ta'mirdagi kabinetlar",
        no_cabinets_found: "Kabinetlar topilmadi",
        add_cabinet: "Kabinet qo'shish",
        details: "Tafsilotlar",
        cabinet: "Kabinet",
        last_maintenance: "Oxirgi ta'mirlash",
        next_maintenance: "Keyingi ta'mirlash",
        select_branch: "Filial tanlang",
        select_type: "Tur tanlang",
        description: "Tavsif",
        no_equipment: "Jihozlar yo'q",
        confirm_delete_cabinet: "Kabinetni o'chirishni tasdiqlaysizmi?",

        // Patients
        add_new_patient: "Yangi bemor qo'shish",
        edit_patient: "Bemorni tahrirlash",
        confirm_delete_patient: "Rostdan ham bu bemorni o'chirmoqchimisiz?",
        age: "Yosh",
        gender: "Jins",
        male: "Erkak",
        female: "Ayol",
        address: "Manzil",
        diagnosis: "Tashxis",
        doctor: "Shifokor",
        last_visit: "Oxirgi tashrif",
        export_to_pdf: "PDF formatida yuklab olish",
        export_to_excel: "Excel formatida yuklab olish",
        blood_group: "Qon guruhi",
        insurance: "Sug'urta",
        emergency_contact: "Favqulodda aloqa",
        allergies: "Allergiyalar",
        medical_history: "Tibbiy tarix",
        patient_id: "Bemor ID",
        registration_date: "Ro'yxatga olingan sana",
        patient_details: "Bemor tafsilotlari",
        patient_list: "Bemorlar ro'yxati",
        patient_statistics: "Bemorlar statistikasi",
        total_patients: "Jami bemorlar",
        new_patients: "Yangi bemorlar",
        returning_patients: "Qaytgan bemorlar",
        patient_demographics: "Bemorlar demografiyasi",
        age_distribution: "Yosh bo'yicha taqsimot",
        gender_distribution: "Jins bo'yicha taqsimot",
        visit_history: "Tashrif tarixi",
        upcoming_appointments: "Kelgusi qabullar",
        treatment_plan: "Davolash rejasi",
        prescriptions: "Retseptlar",
        lab_results: "Laboratoriya natijalari",
        billing_info: "To'lov ma'lumotlari",
        insurance_details: "Sug'urta tafsilotlari",
        insurance_provider: "Sug'urta provayderi",
        policy_number: "Polis raqami",
        coverage_details: "Qamrov tafsilotlari",
        patient_notes: "Bemor qaydlari",
        add_note: "Qayd qo'shish",
        upload_documents: "Hujjatlarni yuklash",
        download_report: "Hisobotni yuklab olish",
        print_details: "Tafsilotlarni chop etish",
        share_records: "Yozuvlarni ulashish",
        filter_by_doctor: "Shifokor bo'yicha filtrlash",
        filter_by_date: "Sana bo'yicha filtrlash",
        filter_by_status: "Holat bo'yicha filtrlash",
        sort_by_name: "Ism bo'yicha saralash",
        sort_by_date: "Sana bo'yicha saralash",
        sort_by_id: "ID bo'yicha saralash",
        inactive_patients: "Nofaol bemorlar",
        patients_count: "Bemorlar soni",
        patients_management: "Bemorlar boshqaruvi",
        search_patients: "Bemorlarni qidirish",
        all_genders: "Barcha jinslar",
        all_statuses: "Barcha holatlar",
        no_patients_found: "Bemorlar topilmadi",
        export: "Eksport",
        import: "Import",
        select_blood_group: "Qon guruhini tanlang",
        save_changes: "O'zgarishlarni saqlash",
        schedule_appointment: "Qabul belgilash",

        // Appointments
        add_new_appointment: "Yangi qabul qo'shish",
        edit_appointment: "Qabulni tahrirlash",
        confirm_delete_appointment: "Rostdan ham bu qabulni o'chirmoqchimisiz?",
        patient: "Bemor",
        date: "Sana",
        time: "Vaqt",
        notes: "Izohlar",
        pending: "Kutilmoqda",
        confirmed: "Tasdiqlangan",
        completed: "Yakunlangan",
        cancelled: "Bekor qilingan",
        select_patient: "Bemorni tanlang",
        select_doctor: "Shifokorni tanlang",
        appointment_details: "Qabul tafsilotlari",
        appointment_history: "Qabul tarixi",
        upcoming_appointments: "Kelgusi qabullar",
        past_appointments: "O'tgan qabullar",
        appointment_status: "Qabul holati",
        reschedule: "Qayta rejalashtirish",
        cancel_appointment: "Qabulni bekor qilish",
        appointment_type: "Qabul turi",
        duration: "Davomiyligi",
        reason: "Sabab",
        symptoms: "Alomatlar",
        appointment_notes: "Qabul qaydlari",
        follow_up: "Keyingi qabul",
        appointment_reminder: "Qabul eslatmasi",
        send_reminder: "Eslatma yuborish",
        reminder_sent: "Eslatma yuborildi",
        appointment_fee: "Qabul to'lovi",
        payment_status: "To'lov holati",
        paid: "To'langan",
        unpaid: "To'lanmagan",
        partial: "Qisman to'langan",
        payment_method: "To'lov usuli",
        cash: "Naqd pul",
        card: "Karta",
        insurance: "Sug'urta",
        appointment_location: "Qabul joyi",
        online: "Onlayn",
        in_person: "Shaxsan",
        appointment_documents: "Qabul hujjatlari",
        upload_documents: "Hujjatlarni yuklash",
        download_documents: "Hujjatlarni yuklab olish",
        appointment_history_empty: "Qabul tarixi bo'sh",
        no_upcoming_appointments: "Kelgusi qabullar yo'q",
        no_past_appointments: "O'tgan qabullar yo'q",
        appointment_created: "Qabul yaratildi",
        appointment_updated: "Qabul yangilandi",
        appointment_deleted: "Qabul o'chirildi",
        appointment_confirmed: "Qabul tasdiqlandi",
        appointment_completed: "Qabul yakunlandi",
        appointment_cancelled: "Qabul bekor qilindi",
        appointment_rescheduled: "Qabul qayta rejalashtirildi",
        select_room: "Xonani tanlang",
        room: "Xona",
        step: "Qadam",
        select_branch_and_patient: "Filial va bemorni tanlang",
        select_date: "Sanani tanlang",
        select_time: "Vaqtni tanlang",
        add_diagnosis_and_notes: "Tashxis va izohlarni qo'shing",
        enter_diagnosis: "Tashxisni kiriting",
        enter_notes: "Izohlarni kiriting",
        next: "Keyingi",
        back: "Orqaga",
        time_already_booked: "Bu vaqt allaqachon band",
        please_select_date_and_room_first: "Iltimos, avval sana va xonani tanlang",
        table_view: "Jadval ko'rinishi",
        calendar_view: "Kalendar ko'rinishi",
        no_appointments: "Qabullar yo'q",
        week_view: "Hafta ko'rinishi",
        day_view: "Kun ko'rinishi",
        no_appointments_for_day: "Bu kun uchun qabullar yo'q",
        in_progress: "Jarayonda",

        // Profile
        personal_info: "Shaxsiy ma'lumotlar",
        change_password: "Parolni o'zgartirish",
        language: "Til",
        save_changes: "O'zgarishlarni saqlash",
        current_password: "Joriy parol",
        new_password: "Yangi parol",
        confirm_new_password: "Yangi parolni tasdiqlang",
        profile_updated: "Profil yangilandi",
        password_changed: "Parol o'zgartirildi",
        passwords_do_not_match: "Parollar mos kelmadi",
        current_password_incorrect: "Joriy parol noto'g'ri",
        profile_picture: "Profil rasmi",
        upload_picture: "Rasm yuklash",
        remove_picture: "Rasmni o'chirish",
        account_settings: "Hisob sozlamalari",
        notification_settings: "Xabarnoma sozlamalari",
        email_notifications: "Email xabarnomalar",
        sms_notifications: "SMS xabarnomalar",
        app_notifications: "Ilova xabarnomalar",
        account_security: "Hisob xavfsizligi",
        two_factor_authentication: "Ikki faktorli autentifikatsiya",
        enable: "Yoqish",
        disable: "O'chirish",
        account_activity: "Hisob faoliyati",
        last_login: "Oxirgi kirish",
        last_password_change: "Oxirgi parol o'zgarishi",
        devices: "Qurilmalar",
        logout_all_devices: "Barcha qurilmalardan chiqish",
        delete_account: "Hisobni o'chirish",
        delete_account_warning: "Bu amal qaytarib bo'lmaydi. Hisobingiz va barcha ma'lumotlaringiz o'chiriladi.",
        confirm_delete_account: "Hisobni o'chirishni tasdiqlang",
        bio: "Biografiya",
        fullName: "To'liq ism",
        passwordMismatch: "Parollar mos kelmadi",
        passwordLength: "Parol uzunligi kamida 6 ta belgi bo'lishi kerak",
        passwordChanged: "Parol muvaffaqiyatli o'zgartirildi",
        changePassword: "Parolni o'zgartirish",

        // Schedule
        schedule: "Jadval",
        availability: "Bandlik",
        working_hours: "Ish soatlari",
        days_off: "Dam olish kunlari",
        vacation: "Ta'til",
        sick_leave: "Kasallik ta'tili",
        personal_leave: "Shaxsiy ta'til",
        schedule_settings: "Jadval sozlamalari",
        auto_schedule: "Avtomatik jadval",
        manual_schedule: "Qo'lda jadval",
        schedule_conflicts: "Jadval ziddiyatlari",
        resolve_conflicts: "Ziddiyatlarni hal qilish",
        schedule_templates: "Jadval shablonlari",
        create_template: "Shablon yaratish",
        apply_template: "Shablonni qo'llash",
        delete_template: "Shablonni o'chirish",
        schedule_export: "Jadvalni eksport qilish",
        import_schedule: "Jadvalni import qilish",
        schedule_notifications: "Jadval xabarnomalar",
        schedule_changes: "Jadval o'zgarishlari",
        schedule_reminders: "Jadval eslatmalari",
        schedule_conflicts_resolved: "Jadval ziddiyatlari hal qilindi",
        schedule_updated: "Jadval yangilandi",
        schedule_template_created: "Jadval shabloni yaratildi",
        schedule_template_applied: "Jadval shabloni qo'llanildi",
        schedule_template_deleted: "Jadval shabloni o'chirildi",
        schedule_exported: "Jadval eksport qilindi",
        schedule_imported: "Jadval import qilindi",
        schedule_notification_sent: "Jadval xabarnomasi yuborildi",
        schedule_reminder_sent: "Jadval eslatmasi yuborildi",
        more: "ko'proq",
        no_tasks: "Vazifalar yo'q",

        // Settings
        generalSettings: "Umumiy sozlamalar",
        branchSettings: "Filial sozlamalari",
        financialSettings: "Moliyaviy sozlamalar",
        userSettings: "Foydalanuvchi sozlamalari",
        notificationSettings: "Xabarnoma sozlamalari",
        securitySettings: "Xavfsizlik sozlamalari",
        systemSettings: "Tizim sozlamalari",
        backupSettings: "Zaxira sozlamalari",
        integrationSettings: "Integratsiya sozlamalari",
        apiSettings: "API sozlamalari",
        branchName: "Filial nomi",
        taxRate: "Soliq stavkasi",
        workingHours: "Ish soatlari",
        workingDays: "Ish kunlari",
        website: "Veb-sayt",

        // Reports
        financialReports: "Moliyaviy hisobotlar",
        patientReports: "Bemor hisobotlari",
        staffReports: "Xodim hisobotlari",
        inventoryReports: "Inventar hisobotlari",
        appointmentReports: "Qabul hisobotlari",
        customReports: "Maxsus hisobotlar",
        reportPeriod: "Hisobot davri",
        daily: "Kunlik",
        weekly: "Haftalik",
        monthly: "Oylik",
        quarterly: "Choraklik",
        yearly: "Yillik",
        customPeriod: "Maxsus davr",
        startDate: "Boshlanish sanasi",
        endDate: "Tugash sanasi",
        generateReport: "Hisobot yaratish",
        exportReport: "Hisobotni eksport qilish",
        printReport: "Hisobotni chop etish",
        saveReport: "Hisobotni saqlash",
        reportGenerated: "Hisobot yaratildi",
        reportExported: "Hisobot eksport qilindi",
        reportPrinted: "Hisobot chop etildi",
        reportSaved: "Hisobot saqlandi",
        noReportData: "Hisobot ma'lumotlari yo'q",
        reportSettings: "Hisobot sozlamalari",
        reportTemplate: "Hisobot shabloni",
        reportFormat: "Hisobot formati",
        includeCharts: "Diagrammalarni qo'shish",
        includeTables: "Jadvallarni qo'shish",
        includeSummary: "Xulosani qo'shish",
        revenueReport: "Daromad hisoboti",
        expenseReport: "Xarajat hisoboti",
        profitReport: "Foyda hisoboti",
        taxReport: "Soliq hisoboti",
        patientVisitReport: "Bemor tashrifi hisoboti",
        staffPerformanceReport: "Xodim samaradorligi hisoboti",
        inventoryUsageReport: "Inventar foydalanish hisoboti",
        appointmentCompletionReport: "Qabul yakunlash hisoboti",

        // Director Reports
        financial: "Moliyaviy",
        income: "Daromad",
        expense: "Xarajat",
        net_profit: "Sof foyda",
        profitability: "Rentabellik",
        financial_indicators: "Moliyaviy ko'rsatkichlar",
        financial_report_details: "Moliyaviy hisobot tafsilotlari",
        total_income: "Jami daromad",
        total_expenses: "Jami xarajat",
        patient_dynamics: "Bemorlar dinamikasi",
        patient_report_details: "Bemorlar hisoboti tafsilotlari",
        average_weekly: "O'rtacha haftalik",
        average_monthly: "O'rtacha oylik",
        average_quarterly: "O'rtacha choraklik",
        average_weekly_patients: "O'rtacha haftalik bemorlar:",
        average_monthly_patients: "O'rtacha oylik bemorlar:",
        average_quarterly_patients: "O'rtacha choraklik bemorlar:",
        growth: "O'sish",
        doctor_efficiency: "Shifokorlar samaradorligi",
        top_performing_doctor: "Eng samarali shifokor",
        average_patients_per_doctor: "O'rtacha bemor soni",
        staff_performance_report: "Xodimlar samaradorligi hisoboti",
        period: "Davr",
        month: "Oy",
        quarter: "Chorak",
        year: "Yil",
        week1: "1-hafta",
        week2: "2-hafta",
        week3: "3-hafta",
        week4: "4-hafta",
        january: "Yanvar",
        february: "Fevral",
        march: "Mart",
        quarter1: "1-chorak",
        quarter2: "2-chorak",
        quarter3: "3-chorak",
        quarter4: "4-chorak",
        history: "Tarix",
        withdraw_cash: "Kassadan pul olish",
        download_report_function: "Hisobot yuklab olish funksiyasi",
        withdrawal_success: "Kassadan pul olish muvaffaqiyatli amalga oshirildi",
        expense_history: "Xarajatlar tarixi",
        category: "Kategoriya",
        amount: "Summa",
        description: "Izoh",
        enter_amount: "Summani kiriting",
        select_reason: "Sababni tanlang",
        enter_additional_description: "Qo'shimcha izoh kiriting",
        confirm: "Tasdiqlash",

        // Withdrawal reasons
        salary: "Shifokorlarga oylik",
        salary_increase: "Shifokorlarga qo'shimcha oylik",
        utilities: "Kommunal to'lovlar",
        rent: "Ijara to'lovi",
        supplies: "Tibbiy jihozlar xaridi",
        medicine: "Dori-darmonlar xaridi",
        repairs: "Ta'mirlash ishlari",
        marketing: "Marketing xarajatlari",
        taxes: "Soliqlar",
        other_expenses: "Boshqa xarajatlar",
        other: "Boshqa",

        // Withdrawal descriptions
        salary_payment_description: "Shifokorlarga oylik maosh to'lovi",
        utilities_payment_description: "Elektr va suv to'lovlari",
        supplies_payment_description: "Yangi tibbiy jihozlar xaridi",
        medicine_payment_description: "Dori-darmonlar xaridi",
        salary_increase_description: "Dr. Aziz Karimovga qo'shimcha oylik",
        rent_payment_description: "Oylik ijara to'lovi",

        // Inpatient Rooms
        inpatient_rooms: "Yotib davolanish xonalari",
        current_rooms: "Joriy xonalar",
        room_history: "Xonalar tarixi",
        add_new_room: "Yangi xona qo'shish",
        edit_room: "Xonani tahrirlash",
        confirm_delete_room: "Rostdan ham bu xonani o'chirmoqchimisiz?",
        room_number: "Xona raqami",
        room_type: "Xona turi",
        standard_room: "Standart xona",
        premium_room: "Premium xona",
        intensive_care: "Intensiv terapiya",
        daily_rate: "Kunlik narx",
        available: "Bo'sh",
        occupied: "Band",
        maintenance: "Ta'mirda",
        room: "Xona",
        type: "Turi",
        capacity: "Sig'imi",
        description: "Tavsif",
        current_patients: "Joriy bemorlar",
        no_patients_in_room: "Bu xonada bemorlar yo'q",
        assign_patient: "Bemorni tayinlash",
        assign_patient_to_room: "Bemorni xonaga tayinlash",
        admission_date: "Qabul qilingan sana",
        expected_discharge_date: "Kutilayotgan chiqish sanasi",
        expected_discharge: "Kutilayotgan chiqish",
        remaining_days: "Qolgan kunlar",
        discharge: "Chiqarish",
        confirm_discharge_patient: "Rostdan ham bu bemorni chiqarmoqchimisiz?",
        add_payment: "To'lov qo'shish",
        add_payment_for: "Uchun to'lov qo'shish",
        payment_method: "To'lov usuli",
        payment_date: "To'lov sanasi",
        total_payment: "Jami to'lov",
        room_occupancy_history: "Xona band bo'lish tarixi",
        discharge_date: "Chiqarilgan sana",
        duration: "Davomiyligi",
        days: "kun",
        no_room_history: "Xona tarixi yo'q",
        inpatient_rooms_statistics: "Yotib davolanish xonalari statistikasi",
        total_rooms: "Jami xonalar",
        available_rooms: "Bo'sh xonalar",
        occupied_rooms: "Band xonalar",
        maintenance_rooms: "Ta'mirdagi xonalar",
        total_inpatients: "Jami yotib davolanuvchilar",
        average_stay_duration: "O'rtacha qolish davomiyligi",
        occupancy_rate: "Band bo'lish darajasi",
        total_revenue: "Jami daromad",
        average_daily_revenue: "O'rtacha kunlik daromad",
        close: "Yopish",
        search_rooms_patients: "Xonalar va bemorlarni qidirish...",
        all_rooms: "Barcha xonalar",
        select_nurse: "Hamshirani tanlang",
        morning_shift: "Ertalabki smena",
        evening_shift: "Kechki smena",
        night_shift: "Tungi smena",
        critical: "Og'ir ahvolda",
        stable: "Barqaror",
        improving: "Tuzalmoqda",

        // Tasks
        tasks_management: "Vazifalar boshqaruvi",
        calendar_view: "Kalendar ko'rinishi",
        list_view: "Ro'yxat ko'rinishi",
        add_task: "Vazifa qo'shish",
        search_tasks: "Vazifalarni qidirish",
        no_tasks_found: "Vazifalar topilmadi",
        task_title: "Vazifa sarlavhasi",
        start_time: "Boshlanish vaqti",
        end_time: "Tugash vaqti",
        select_assignee: "Bajaruvchini tanlang",
        create_task: "Vazifa yaratish",
        update_task: "Vazifani yangilash",
        mark_complete: "Bajarildi deb belgilash",
        start_task: "Vazifani boshlash",
        reopen_task: "Vazifani qayta ochish",
        task_details: "Vazifa tafsilotlari",
        no_description: "Tavsif yo'q",
        please_select_assignee: "Iltimos, bajaruvchini tanlang",
    },
    ru: {
        // Auth
        login: "Вход",
        signup: "Регистрация",
        logout: "Выход",
        email: "Email",
        password: "Пароль",
        confirm_password: "Подтвердите пароль",
        forgot_password: "Забыли пароль?",
        remember_me: "Запомнить меня",
        request_access: "Запросить доступ",
        loggingIn: "Вход...",
        or: "или",
        noAccount: "Нет аккаунта?",
        signUp: "Зарегистрироваться",
        requestReceived: "Ваш запрос получен",
        credentialsSentTo: "Данные для входа будут отправлены на:",
        backToLogin: "Вернуться к входу",
        loginInstructions: "Введите данные для входа в систему",
        emailPasswordRequired: "Требуется ввести email и пароль",
        loginFailed: "Не удалось войти",
        clinicName: "Название клиники",
        enterClinicInfo: "Введите информацию о клинике",
        submit: "Отправить",
        back: "Назад",

        // Roles
        director: "Директор",
        admin: "Администратор",
        doctor: "Врач",
        user: "Пользователь",
        nurse: "Медсестра",

        // Dashboard
        dashboard: "Панель управления",
        staff: "Персонал",
        cabinets: "Кабинеты",
        patients: "Пациенты",
        appointments: "Приемы",
        reports: "Отчеты",
        settings: "Настройки",
        notifications: "Уведомления",
        profile: "Профиль",
        loading: "Загрузка",
        allBranches: "Все филиалы",

        // Main Menu
        main_menu: "Главное меню",
        home: "Главная",
        account: "Аккаунт",
        help: "Помощь",
        help_center: "Центр помощи",

        // Patient Care
        patient_care: "Уход за пациентами",
        vital_signs: "Жизненные показатели",
        medications: "Лекарства",

        // Additional terms
        finance: "Финансы",
        all_staff: "Весь персонал",
        doctors: "Врачи",
        nurses: "Медсестры",
        all_rights_reserved: "Все права защищены",
        privacy_policy: "Политика конфиденциальности",
        terms_of_service: "Условия обслуживания",
        minutesAgo: "минут назад",
        hoursAgo: "часов назад",
        new_patient_added: "Добавлен новый пациент",
        appointment_reminder: "Напоминание о приеме",
        system_updated: "Система обновлена",
        room_maintenance_completed: "Обслуживание палаты завершено",
        patients_today: "Пациенты сегодня",
        appointments_today: "Приемы сегодня",
        error_occurred: "Произошла ошибка",
        try_again: "Попробуйте снова",

        // Common
        search: "Поиск...",
        filters: "Фильтры",
        all: "Все",
        active: "Активный",
        inactive: "Неактивный",
        add: "Добавить",
        save: "Сохранить",
        cancel: "Отмена",
        edit: "Редактировать",
        delete: "Удалить",
        actions: "Действия",
        name: "Имя",
        status: "Статус",
        branch: "Филиал",
        branch1: "Филиал 1",
        branch2: "Филиал 2",
        branch3: "Филиал 3",
        no_data_found: "Данные не найдены",
        statistics: "Статистика",
        close_stats: "Закрыть статистику",
        today: "Сегодня",
        yesterday: "Вчера",
        daysAgo: "дней назад",
        markAllAsRead: "Отметить все как прочитанные",
        markAsRead: "Отметить как прочитанное",
        read: "Прочитано",
        unread: "Непрочитано",
        siteNews: "Новости сайта",
        workNotifications: "Рабочие уведомления",
        noNotifications: "Нет уведомлений",
        high: "Высокий",
        medium: "Средний",
        low: "Низкий",
        priority: "Приоритет",
        settingsSaved: "Настройки сохранены",
        guest: "Гость",

        // Staff
        add_new_staff: "Добавить нового сотрудника",
        edit_staff: "Редактировать сотрудника",
        confirm_delete_staff: "Вы действительно хотите удалить этого сотрудника?",
        position: "Должность",
        department: "Отдел",
        phone: "Телефон",
        monthly_salary: "Ежемесячная зарплата",
        vacation_status: "Статус отпуска",
        on_vacation: "В отпуске",
        at_work: "На работе",
        vacation_period: "Период отпуска",
        vacation_period_example: "Пример: 2023-05-20 - 2023-06-05",
        full_name: "Полное имя",
        total_staff: "Всего сотрудников",
        active_staff: "Активные сотрудники",
        staff_on_vacation: "Сотрудники в отпуске",
        total_salary: "Общая зарплата",
        role_distribution: "Распределение по должностям",
        currency: "сум",
        inactive_staff: "Неактивные сотрудники",

        // Staff positions
        doctor: "Врач",
        admin: "Администратор",
        nurse: "Медсестра",
        lab_technician: "Лаборант",
        pharmacist: "Фармацевт",
        receptionist: "Регистратор",
        accountant: "Бухгалтер",
        cleaner: "Уборщик",
        security: "Охранник",
        buyer: "Специалист по закупкам",
        manager: "Менеджер",

        // Cabinets
        add_new_cabinet: "Добавить новый кабинет",
        edit_cabinet: "Редактировать кабинет",
        confirm_delete_cabinet: "Вы действительно хотите удалить этот кабинет?",
        cabinet_number: "Номер кабинета",
        cabinet_name: "Название кабинета",
        floor: "Этаж",
        capacity: "Вместимость",
        doctors_count: "количество врачей",
        maintenance: "На ремонте",
        total_cabinets: "Всего кабинетов",
        active_cabinets: "Активные кабинеты",
        maintenance_cabinets: "Кабинеты на ремонте",
        total_capacity: "Общая вместимость",
        floor_distribution: "Распределение по этажам",
        number: "Номер",
        inactive_cabinets: "Неактивные кабинеты",
        examination: "Осмотр",
        procedure: "Процедура",
        surgery: "Хирургия",
        laboratory: "Лаборатория",
        x_ray: "Рентген",
        type: "Тип",
        equipment: "Оборудование",
        type_distribution: "Распределение по типам",
        available: "Доступен",
        occupied: "Занят",
        cabinets_management: "Управление кабинетами",
        search_cabinets: "Поиск кабинетов",
        all_types: "Все типы",
        examination_room: "Кабинет осмотра",
        procedure_room: "Процедурный кабинет",
        surgery_room: "Операционная",
        laboratory: "Лаборатория",
        dental_room: "Стоматологический кабинет",
        all_branches: "Все филиалы",
        available_cabinets: "Доступные кабинеты",
        occupied_cabinets: "Занятые кабинеты",
        maintenance_cabinets: "Кабинеты на ремонте",
        no_cabinets_found: "Кабинеты не найдены",
        add_cabinet: "Добавить кабинет",
        details: "Детали",
        cabinet: "Кабинет",
        last_maintenance: "Последнее обслуживание",
        next_maintenance: "Следующее обслуживание",
        select_branch: "Выберите филиал",
        select_type: "Выберите тип",
        description: "Описание",
        no_equipment: "Нет оборудования",
        confirm_delete_cabinet: "Подтвердите удаление кабинета",

        // Patients
        add_new_patient: "Добавить нового пациента",
        edit_patient: "Редактировать пациента",
        confirm_delete_patient: "Вы действительно хотите удалить этого пациента?",
        age: "Возраст",
        gender: "Пол",
        male: "Мужской",
        female: "Женский",
        address: "Адрес",
        diagnosis: "Диагноз",
        doctor: "Врач",
        last_visit: "Последний визит",
        export_to_pdf: "Экспорт в PDF",
        export_to_excel: "Экспорт в Excel",
        blood_group: "Группа крови",
        insurance: "Страховка",
        emergency_contact: "Экстренный контакт",
        allergies: "Аллергии",
        medical_history: "История болезни",
        patient_id: "ID пациента",
        registration_date: "Дата регистрации",
        patient_details: "Детали пациента",
        patient_list: "Список пациентов",
        patient_statistics: "Статистика пациентов",
        total_patients: "Всего пациентов",
        new_patients: "Новые пациенты",
        returning_patients: "Вернувшиеся пациенты",
        patient_demographics: "Демография пациентов",
        age_distribution: "Распределение по возрасту",
        gender_distribution: "Распределение по полу",
        visit_history: "История посещений",
        upcoming_appointments: "Предстоящие приемы",
        treatment_plan: "План лечения",
        prescriptions: "Рецепты",
        lab_results: "Результаты анализов",
        billing_info: "Платежная информация",
        insurance_details: "Детали страховки",
        insurance_provider: "Страховая компания",
        policy_number: "Номер полиса",
        coverage_details: "Детали покрытия",
        patient_notes: "Заметки о пациенте",
        add_note: "Добавить заметку",
        upload_documents: "Загрузить документы",
        download_report: "Скачать отчет",
        print_details: "Распечатать детали",
        share_records: "Поделиться записями",
        filter_by_doctor: "Фильтр по врачу",
        filter_by_date: "Фильтр по дате",
        filter_by_status: "Фильтр по статусу",
        sort_by_name: "Сортировать по имени",
        sort_by_date: "Сортировать по дате",
        sort_by_id: "Сортировать по ID",
        inactive_patients: "Неактивные пациенты",
        patients_count: "Количество пациентов",
        patients_management: "Управление пациентами",
        search_patients: "Поиск пациентов",
        all_genders: "Все полы",
        all_statuses: "Все статусы",
        no_patients_found: "Пациенты не найдены",
        export: "Экспорт",
        import: "Импорт",
        select_blood_group: "Выберите группу крови",
        save_changes: "Сохранить изменения",
        schedule_appointment: "Назначить прием",

        // Appointments
        add_new_appointment: "Добавить новый прием",
        edit_appointment: "Редактировать прием",
        confirm_delete_appointment: "Вы действительно хотите удалить этот прием?",
        patient: "Пациент",
        date: "Дата",
        time: "Время",
        notes: "Примечания",
        pending: "Ожидается",
        confirmed: "Подтвержден",
        completed: "Завершен",
        cancelled: "Отменен",
        select_patient: "Выберите пациента",
        select_doctor: "Выберите врача",
        appointment_details: "Детали приема",
        appointment_history: "История приемов",
        upcoming_appointments: "Предстоящие приемы",
        past_appointments: "Прошедшие приемы",
        appointment_status: "Статус приема",
        reschedule: "Перенести",
        cancel_appointment: "Отменить прием",
        appointment_type: "Тип приема",
        duration: "Продолжительность",
        reason: "Причина",
        symptoms: "Симптомы",
        appointment_notes: "Заметки о приеме",
        follow_up: "Последующий прием",
        appointment_reminder: "Напоминание о приеме",
        send_reminder: "Отправить напоминание",
        reminder_sent: "Напоминание отправлено",
        appointment_fee: "Стоимость приема",
        payment_status: "Статус оплаты",
        paid: "Оплачено",
        unpaid: "Не оплачено",
        partial: "Частично оплачено",
        payment_method: "Способ оплаты",
        cash: "Наличные",
        card: "Карта",
        insurance: "Страховка",
        appointment_location: "Место приема",
        online: "Онлайн",
        in_person: "Лично",
        appointment_documents: "Документы приема",
        upload_documents: "Загрузить документы",
        download_documents: "Скачать документы",
        appointment_history_empty: "История приемов пуста",
        no_upcoming_appointments: "Нет предстоящих приемов",
        no_past_appointments: "Нет прошедших приемов",
        appointment_created: "Прием создан",
        appointment_updated: "Прием обновлен",
        appointment_deleted: "Прием удален",
        appointment_confirmed: "Прием подтвержден",
        appointment_completed: "Прием завершен",
        appointment_cancelled: "Прием отменен",
        appointment_rescheduled: "Прием перенесен",
        select_room: "Выберите кабинет",
        room: "Кабинет",
        step: "Шаг",
        select_branch_and_patient: "Выберите филиал и пациента",
        select_date: "Выберите дату",
        select_time: "Выберите время",
        add_diagnosis_and_notes: "Добавьте диагноз и примечания",
        enter_diagnosis: "Введите диагноз",
        enter_notes: "Введите примечания",
        next: "Далее",
        back: "Назад",
        time_already_booked: "Это время уже занято",
        please_select_date_and_room_first: "Пожалуйста, сначала выберите дату и кабинет",
        table_view: "Табличный вид",
        calendar_view: "Календарный вид",
        no_appointments: "Нет приемов",
        week_view: "Недельный вид",
        day_view: "Дневной вид",
        no_appointments_for_day: "Нет приемов на этот день",
        in_progress: "В процессе",

        // Profile
        personal_info: "Личная информация",
        change_password: "Изменить пароль",
        language: "Язык",
        save_changes: "Сохранить изменения",
        current_password: "Текущий пароль",
        new_password: "Новый пароль",
        confirm_new_password: "Подтвердите новый пароль",
        profile_updated: "Профиль обновлен",
        password_changed: "Пароль изменен",
        passwords_do_not_match: "Пароли не совпадают",
        current_password_incorrect: "Текущий пароль неверен",
        profile_picture: "Изображение профиля",
        upload_picture: "Загрузить изображение",
        remove_picture: "Удалить изображение",
        account_settings: "Настройки аккаунта",
        notification_settings: "Настройки уведомлений",
        email_notifications: "Email уведомления",
        sms_notifications: "SMS уведомления",
        app_notifications: "Уведомления приложения",
        account_security: "Безопасность аккаунта",
        two_factor_authentication: "Двухфакторная аутентификация",
        enable: "Включить",
        disable: "Отключить",
        account_activity: "Активность аккаунта",
        last_login: "Последний вход",
        last_password_change: "Последнее изменение пароля",
        devices: "Устройства",
        logout_all_devices: "Выйти со всех устройств",
        delete_account: "Удалить аккаунт",
        delete_account_warning: "Это действие необратимо. Ваш аккаунт и все данные будут удалены.",
        confirm_delete_account: "Подтвердите удаление аккаунта",
        bio: "Биография",
        fullName: "Полное имя",
        passwordMismatch: "Пароли не совпадают",
        passwordLength: "Длина пароля должна быть не менее 6 символов",
        passwordChanged: "Пароль успешно изменен",
        changePassword: "Изменить пароль",

        // Schedule
        schedule: "Расписание",
        availability: "Доступность",
        working_hours: "Рабочие часы",
        days_off: "Выходные дни",
        vacation: "Отпуск",
        sick_leave: "Больничный",
        personal_leave: "Личный отпуск",
        schedule_settings: "Настройки расписания",
        auto_schedule: "Автоматическое расписание",
        manual_schedule: "Ручное расписание",
        schedule_conflicts: "Конфликты расписания",
        resolve_conflicts: "Разрешить конфликты",
        schedule_templates: "Шаблоны расписания",
        create_template: "Создать шаблон",
        apply_template: "Применить шаблон",
        delete_template: "Удалить шаблон",
        schedule_export: "Экспорт расписания",
        import_schedule: "Импорт расписания",
        schedule_notifications: "Уведомления о ра��писании",
        schedule_changes: "Изменения в расписании",
        schedule_reminders: "Напоминания о расписании",
        schedule_conflicts_resolved: "Конфликты расписания разрешены",
        schedule_updated: "Расписание обновлено",
        schedule_template_created: "Шаблон расписания создан",
        schedule_template_applied: "Шаблон расписания применен",
        schedule_template_deleted: "Шаблон расписания удален",
        schedule_exported: "Расписание экспортировано",
        schedule_imported: "Расписание импортировано",
        schedule_notification_sent: "Уведомление о расписании отправлено",
        schedule_reminder_sent: "Напоминание о расписании отправлено",
        more: "еще",
        no_tasks: "Нет задач",

        // Settings
        generalSettings: "Общие настройки",
        branchSettings: "Настройки филиалов",
        financialSettings: "Финансовые настройки",
        userSettings: "Настройки пользователя",
        notificationSettings: "Настройки уведомлений",
        securitySettings: "Настройки безопасности",
        systemSettings: "Системные настройки",
        backupSettings: "Настройки резервного копирования",
        integrationSettings: "Настройки интеграции",
        apiSettings: "Настройки API",
        branchName: "Название филиала",
        taxRate: "Налоговая ставка",
        workingHours: "Рабочие часы",
        workingDays: "Рабочие дни",
        website: "Веб-сайт",

        // Reports
        financialReports: "Финансовые отчеты",
        patientReports: "Отчеты по пациентам",
        staffReports: "Отчеты по персоналу",
        inventoryReports: "Отчеты по инвентарю",
        appointmentReports: "Отчеты по приемам",
        customReports: "Пользовательские отчеты",
        reportPeriod: "Период отчета",
        daily: "Ежедневно",
        weekly: "Еженедельно",
        monthly: "Ежемесячно",
        quarterly: "Ежеквартально",
        yearly: "Ежегодно",
        customPeriod: "Пользовательский период",
        startDate: "Дата начала",
        endDate: "Дата окончания",
        generateReport: "Сгенерировать отчет",
        exportReport: "Экспортировать отчет",
        printReport: "Распечатать отчет",
        saveReport: "Сохранить отчет",
        reportGenerated: "Отчет сгенерирован",
        reportExported: "Отчет экспортирован",
        reportPrinted: "Отчет распечатан",
        reportSaved: "Отчет сохранен",
        noReportData: "Нет данных для отчета",
        reportSettings: "Настройки отчета",
        reportTemplate: "Шаблон отчета",
        reportFormat: "Формат отчета",
        includeCharts: "Включить диаграммы",
        includeTables: "Включить таблицы",
        includeSummary: "Включить сводку",
        revenueReport: "Отчет о доходах",
        expenseReport: "Отчет о расходах",
        profitReport: "Отчет о прибыли",
        taxReport: "Налоговый отчет",
        patientVisitReport: "Отчет о посещениях пациентов",
        staffPerformanceReport: "Отчет о производительности персонала",
        inventoryUsageReport: "Отчет об использовании инвентаря",
        appointmentCompletionReport: "Отчет о завершении приемов",

        // Director Reports
        financial: "Финансовый",
        income: "Доход",
        expense: "Расход",
        net_profit: "Чистая прибыль",
        profitability: "Рентабельность",
        financial_indicators: "Финансовые показатели",
        financial_report_details: "Детали финансового отчета",
        total_income: "Общий доход",
        total_expenses: "Общие расходы",
        patient_dynamics: "Динамика пациентов",
        patient_report_details: "Детали отчета по пациентам",
        average_weekly: "Среднее за неделю",
        average_monthly: "Среднее за месяц",
        average_quarterly: "Среднее за квартал",
        average_weekly_patients: "Среднее количество пациентов за неделю:",
        average_monthly_patients: "Среднее количество пациентов за месяц:",
        average_quarterly_patients: "Среднее количество пациентов за квартал:",
        growth: "Рост",
        doctor_efficiency: "Эффективность врачей",
        top_performing_doctor: "Лучший врач",
        average_patients_per_doctor: "Среднее количество пациентов на врача",
        staff_performance_report: "Отчет о производительности персонала",
        period: "Период",
        month: "Месяц",
        quarter: "Квартал",
        year: "Год",
        week1: "1-я неделя",
        week2: "2-я неделя",
        week3: "3-я неделя",
        week4: "4-я неделя",
        january: "Январь",
        february: "Февраль",
        march: "Март",
        quarter1: "1-й квартал",
        quarter2: "2-й квартал",
        quarter3: "3-й квартал",
        quarter4: "4-й квартал",
        history: "История",
        withdraw_cash: "Снять деньги из кассы",
        download_report_function: "Функция загрузки отчета",
        withdrawal_success: "Снятие денег из кассы успешно выполнено",
        expense_history: "История расходов",
        category: "Категория",
        amount: "Сумма",
        description: "Описание",
        enter_amount: "Введите сумму",
        select_reason: "Выберите причину",
        enter_additional_description: "Введите дополнительное описание",
        confirm: "Подтвердить",

        // Withdrawal reasons
        salary: "Зарплата врачам",
        salary_increase: "Дополнительная зарплата врачам",
        utilities: "Коммунальные платежи",
        rent: "Арендная плата",
        supplies: "Покупка медицинского оборудования",
        medicine: "Покупка лекарств",
        repairs: "Ремонтные работы",
        marketing: "Маркетинговые расходы",
        taxes: "Налоги",
        other_expenses: "Другие расходы",
        other: "Другое",

        // Withdrawal descriptions
        salary_payment_description: "Выплата ежемесячной зарплаты врачам",
        utilities_payment_description: "Оплата электричества и воды",
        supplies_payment_description: "Покупка нового медицинского оборудования",
        medicine_payment_description: "Покупка лекарств",
        salary_increase_description: "Дополнительная зарплата для Др. Азиза Каримова",
        rent_payment_description: "Ежемесячная арендная плата",

        // Inpatient Rooms
        inpatient_rooms: "Палаты для стационарных больных",
        current_rooms: "Текущие палаты",
        room_history: "История палат",
        add_new_room: "Добавить новую палату",
        edit_room: "Редактировать палату",
        confirm_delete_room: "Вы действительно хотите удалить эту палату?",
        room_number: "Номер палаты",
        room_type: "Тип палаты",
        standard_room: "Стандартная палата",
        premium_room: "Премиум палата",
        intensive_care: "Интенсивная терапия",
        daily_rate: "Дневная ставка",
        available: "Доступна",
        occupied: "Занята",
        maintenance: "На ремонте",
        room: "Палата",
        type: "Тип",
        capacity: "Вместимость",
        description: "Описание",
        current_patients: "Текущие пациенты",
        no_patients_in_room: "В этой палате нет пациентов",
        assign_patient: "Назначить пациента",
        assign_patient_to_room: "Назначить пациента в палату",
        admission_date: "Дата поступления",
        expected_discharge_date: "Ожидаемая дата выписки",
        expected_discharge: "Ожидаемая выписка",
        remaining_days: "Оставшиеся дни",
        discharge: "Выписать",
        confirm_discharge_patient: "Вы действительно хотите выписать этого пациента?",
        add_payment: "Добавить оплату",
        add_payment_for: "Добавить оплату для",
        payment_method: "Способ оплаты",
        payment_date: "Дата оплаты",
        total_payment: "Общая оплата",
        room_occupancy_history: "История занятости палат",
        discharge_date: "Дата выписки",
        duration: "Продолжительность",
        days: "дней",
        no_room_history: "Нет истории палат",
        inpatient_rooms_statistics: "Статистика стационарных палат",
        total_rooms: "Всего палат",
        available_rooms: "Доступные палаты",
        occupied_rooms: "Занятые палаты",
        maintenance_rooms: "Палаты на ремонте",
        total_inpatients: "Всего стационарных пациентов",
        average_stay_duration: "Средняя продолжительность пребывания",
        occupancy_rate: "Уровень занятости",
        total_revenue: "Общий доход",
        average_daily_revenue: "Средний дневной доход",
        close: "Закрыть",
        search_rooms_patients: "Поиск палат и пациентов...",
        all_rooms: "Все палаты",
        select_nurse: "Выберите медсестру",
        morning_shift: "Утренняя смена",
        evening_shift: "Вечерняя смена",
        night_shift: "Ночная смена",
        critical: "В критическом состоянии",
        stable: "Стабильный",
        improving: "Улучшение",

        // Tasks
        tasks_management: "Управление задачами",
        calendar_view: "Календарный вид",
        list_view: "Список",
        add_task: "Добавить задачу",
        search_tasks: "Поиск задач",
        no_tasks_found: "Задачи не найдены",
        task_title: "Название задачи",
        start_time: "Время начала",
        end_time: "Время окончания",
        select_assignee: "Выберите исполнителя",
        create_task: "Создать задачу",
        update_task: "Обновить задачу",
        mark_complete: "Отметить как выполненную",
        start_task: "Начать задачу",
        reopen_task: "Переоткрыть задачу",
        task_details: "Детали задачи",
        no_description: "Нет описания",
        please_select_assignee: "Пожалуйста, выберите исполнителя",
    },
    en: {
        // Auth
        login: "Login",
        signup: "Sign Up",
        logout: "Logout",
        email: "Email",
        password: "Password",
        confirm_password: "Confirm Password",
        forgot_password: "Forgot Password?",
        remember_me: "Remember Me",
        request_access: "Request Access",
        loggingIn: "Logging in...",
        or: "or",
        noAccount: "Don't have an account?",
        signUp: "Sign Up",
        requestReceived: "Request Received",
        credentialsSentTo: "Login credentials will be sent to:",
        backToLogin: "Back to Login",
        loginInstructions: "Enter your credentials to log in",
        emailPasswordRequired: "Email and password are required",
        loginFailed: "Login failed",
        clinicName: "Clinic Name",
        enterClinicInfo: "Enter clinic information",
        submit: "Submit",
        back: "Back",

        // Roles
        director: "Director",
        admin: "Administrator",
        doctor: "Doctor",
        user: "User",
        nurse: "Nurse",

        // Dashboard
        dashboard: "Dashboard",
        staff: "Staff",
        cabinets: "Cabinets",
        patients: "Patients",
        appointments: "Appointments",
        reports: "Reports",
        settings: "Settings",
        notifications: "Notifications",
        profile: "Profile",
        loading: "Loading",
        allBranches: "All Branches",

        // Main Menu
        main_menu: "Main Menu",
        home: "Home",
        account: "Account",
        help: "Help",
        help_center: "Help Center",

        // Patient Care
        patient_care: "Patient Care",
        vital_signs: "Vital Signs",
        medications: "Medications",

        // Additional terms
        finance: "Finance",
        all_staff: "All Staff",
        doctors: "Doctors",
        nurses: "Nurses",
        all_rights_reserved: "All rights reserved",
        privacy_policy: "Privacy Policy",
        terms_of_service: "Terms of Service",
        minutesAgo: "minutes ago",
        hoursAgo: "hours ago",
        new_patient_added: "New patient added",
        appointment_reminder: "Appointment reminder",
        system_updated: "System updated",
        room_maintenance_completed: "Room maintenance completed",
        patients_today: "Patients today",
        appointments_today: "Appointments today",
        error_occurred: "An error occurred",
        try_again: "Try again",

        // Common
        search: "Search...",
        filters: "Filters",
        all: "All",
        active: "Active",
        inactive: "Inactive",
        add: "Add",
        save: "Save",
        cancel: "Cancel",
        edit: "Edit",
        delete: "Delete",
        actions: "Actions",
        name: "Name",
        status: "Status",
        branch: "Branch",
        branch1: "Branch 1",
        branch2: "Branch 2",
        branch3: "Branch 3",
        no_data_found: "No data found",
        statistics: "Statistics",
        close_stats: "Close Statistics",
        today: "Today",
        yesterday: "Yesterday",
        daysAgo: "days ago",
        markAllAsRead: "Mark All as Read",
        markAsRead: "Mark as Read",
        read: "Read",
        unread: "Unread",
        siteNews: "Site News",
        workNotifications: "Work Notifications",
        noNotifications: "No notifications",
        high: "High",
        medium: "Medium",
        low: "Low",
        priority: "Priority",
        settingsSaved: "Settings saved",
        guest: "Guest",

        // Staff
        add_new_staff: "Add New Staff",
        edit_staff: "Edit Staff",
        confirm_delete_staff: "Are you sure you want to delete this staff member?",
        position: "Position",
        department: "Department",
        phone: "Phone",
        monthly_salary: "Monthly Salary",
        vacation_status: "Vacation Status",
        on_vacation: "On Vacation",
        at_work: "At Work",
        vacation_period: "Vacation Period",
        vacation_period_example: "Example: 2023-05-20 - 2023-06-05",
        full_name: "Full Name",
        total_staff: "Total Staff",
        active_staff: "Active Staff",
        staff_on_vacation: "Staff on Vacation",
        total_salary: "Total Salary",
        role_distribution: "Role Distribution",
        currency: "sum",
        inactive_staff: "Inactive Staff",

        // Staff positions
        doctor: "Doctor",
        admin: "Admin",
        nurse: "Nurse",
        lab_technician: "Lab Technician",
        pharmacist: "Pharmacist",
        receptionist: "Receptionist",
        accountant: "Accountant",
        cleaner: "Cleaner",
        security: "Security",
        buyer: "Purchasing Specialist",
        manager: "Manager",

        // Cabinets
        add_new_cabinet: "Add New Cabinet",
        edit_cabinet: "Edit Cabinet",
        confirm_delete_cabinet: "Are you sure you want to delete this cabinet?",
        cabinet_number: "Cabinet Number",
        cabinet_name: "Cabinet Name",
        floor: "Floor",
        capacity: "Capacity",
        doctors_count: "doctors count",
        maintenance: "Under Maintenance",
        total_cabinets: "Total Cabinets",
        active_cabinets: "Active Cabinets",
        maintenance_cabinets: "Cabinets Under Maintenance",
        total_capacity: "Total Capacity",
        floor_distribution: "Floor Distribution",
        number: "Number",
        inactive_cabinets: "Inactive Cabinets",
        examination: "Examination",
        procedure: "Procedure",
        surgery: "Surgery",
        laboratory: "Laboratory",
        x_ray: "X-Ray",
        type: "Type",
        equipment: "Equipment",
        type_distribution: "Type Distribution",
        available: "Available",
        occupied: "Occupied",
        cabinets_management: "Cabinets Management",
        search_cabinets: "Search Cabinets",
        all_types: "All Types",
        examination_room: "Examination Room",
        procedure_room: "Procedure Room",
        surgery_room: "Surgery Room",
        laboratory: "Laboratory",
        dental_room: "Dental Room",
        all_branches: "All Branches",
        available_cabinets: "Available Cabinets",
        occupied_cabinets: "Occupied Cabinets",
        maintenance_cabinets: "Maintenance Cabinets",
        no_cabinets_found: "No Cabinets Found",
        add_cabinet: "Add Cabinet",
        details: "Details",
        cabinet: "Cabinet",
        last_maintenance: "Last Maintenance",
        next_maintenance: "Next Maintenance",
        select_branch: "Select Branch",
        select_type: "Select Type",
        description: "Description",
        no_equipment: "No Equipment",
        confirm_delete_cabinet: "Confirm Delete Cabinet",

        // Patients
        add_new_patient: "Add New Patient",
        edit_patient: "Edit Patient",
        confirm_delete_patient: "Are you sure you want to delete this patient?",
        age: "Age",
        gender: "Gender",
        male: "Male",
        female: "Female",
        address: "Address",
        diagnosis: "Diagnosis",
        doctor: "Doctor",
        last_visit: "Last Visit",
        export_to_pdf: "Export to PDF",
        export_to_excel: "Export to Excel",
        blood_group: "Blood Group",
        insurance: "Insurance",
        emergency_contact: "Emergency Contact",
        allergies: "Allergies",
        medical_history: "Medical History",
        patient_id: "Patient ID",
        registration_date: "Registration Date",
        patient_details: "Patient Details",
        patient_list: "Patient List",
        patient_statistics: "Patient Statistics",
        total_patients: "Total Patients",
        new_patients: "New Patients",
        returning_patients: "Returning Patients",
        patient_demographics: "Patient Demographics",
        age_distribution: "Age Distribution",
        gender_distribution: "Gender Distribution",
        visit_history: "Visit History",
        upcoming_appointments: "Upcoming Appointments",
        treatment_plan: "Treatment Plan",
        prescriptions: "Prescriptions",
        lab_results: "Lab Results",
        billing_info: "Billing Information",
        insurance_details: "Insurance Details",
        insurance_provider: "Insurance Provider",
        policy_number: "Policy Number",
        coverage_details: "Coverage Details",
        patient_notes: "Patient Notes",
        add_note: "Add Note",
        upload_documents: "Upload Documents",
        download_report: "Download Report",
        print_details: "Print Details",
        share_records: "Share Records",
        filter_by_doctor: "Filter by Doctor",
        filter_by_date: "Filter by Date",
        filter_by_status: "Filter by Status",
        sort_by_name: "Sort by Name",
        sort_by_date: "Sort by Date",
        sort_by_id: "Sort by ID",
        inactive_patients: "Inactive Patients",
        patients_count: "Patients Count",
        patients_management: "Patients Management",
        search_patients: "Search Patients",
        all_genders: "All Genders",
        all_statuses: "All Statuses",
        no_patients_found: "No Patients Found",
        export: "Export",
        import: "Import",
        select_blood_group: "Select Blood Group",
        save_changes: "Save Changes",
        schedule_appointment: "Schedule Appointment",

        // Appointments
        add_new_appointment: "Add New Appointment",
        edit_appointment: "Edit Appointment",
        confirm_delete_appointment: "Are you sure you want to delete this appointment?",
        patient: "Patient",
        date: "Date",
        time: "Time",
        notes: "Notes",
        pending: "Pending",
        confirmed: "Confirmed",
        completed: "Completed",
        cancelled: "Cancelled",
        select_patient: "Select Patient",
        select_doctor: "Select Doctor",
        appointment_details: "Appointment Details",
        appointment_history: "Appointment History",
        upcoming_appointments: "Upcoming Appointments",
        past_appointments: "Past Appointments",
        appointment_status: "Appointment Status",
        reschedule: "Reschedule",
        cancel_appointment: "Cancel Appointment",
        appointment_type: "Appointment Type",
        duration: "Duration",
        reason: "Reason",
        symptoms: "Symptoms",
        appointment_notes: "Appointment Notes",
        follow_up: "Follow Up",
        appointment_reminder: "Appointment Reminder",
        send_reminder: "Send Reminder",
        reminder_sent: "Reminder Sent",
        appointment_fee: "Appointment Fee",
        payment_status: "Payment Status",
        paid: "Paid",
        unpaid: "Unpaid",
        partial: "Partial",
        payment_method: "Payment Method",
        cash: "Cash",
        card: "Card",
        insurance: "Insurance",
        appointment_location: "Appointment Location",
        online: "Online",
        in_person: "In Person",
        appointment_documents: "Appointment Documents",
        upload_documents: "Upload Documents",
        download_documents: "Download Documents",
        appointment_history_empty: "Appointment History Empty",
        no_upcoming_appointments: "No Upcoming Appointments",
        no_past_appointments: "No Past Appointments",
        appointment_created: "Appointment Created",
        appointment_updated: "Appointment Updated",
        appointment_deleted: "Appointment Deleted",
        appointment_confirmed: "Appointment Confirmed",
        appointment_completed: "Appointment Completed",
        appointment_cancelled: "Appointment Cancelled",
        appointment_rescheduled: "Appointment Rescheduled",
        select_room: "Select Room",
        room: "Room",
        step: "Step",
        select_branch_and_patient: "Select Branch and Patient",
        select_date: "Select Date",
        select_time: "Select Time",
        add_diagnosis_and_notes: "Add Diagnosis and Notes",
        enter_diagnosis: "Enter Diagnosis",
        enter_notes: "Enter Notes",
        next: "Next",
        back: "Back",
        time_already_booked: "This time is already booked",
        please_select_date_and_room_first: "Please select date and room first",
        table_view: "Table View",
        calendar_view: "Calendar View",
        no_appointments: "No Appointments",
        week_view: "Week View",
        day_view: "Day View",
        no_appointments_for_day: "No Appointments for This Day",
        in_progress: "In Progress",

        // Profile
        personal_info: "Personal Information",
        change_password: "Change Password",
        language: "Language",
        save_changes: "Save Changes",
        current_password: "Current Password",
        new_password: "New Password",
        confirm_new_password: "Confirm New Password",
        profile_updated: "Profile Updated",
        password_changed: "Password Changed",
        passwords_do_not_match: "Passwords do not match",
        current_password_incorrect: "Current password is incorrect",
        profile_picture: "Profile Picture",
        upload_picture: "Upload Picture",
        remove_picture: "Remove Picture",
        account_settings: "Account Settings",
        notification_settings: "Notification Settings",
        email_notifications: "Email Notifications",
        sms_notifications: "SMS Notifications",
        app_notifications: "App Notifications",
        account_security: "Account Security",
        two_factor_authentication: "Two-Factor Authentication",
        enable: "Enable",
        disable: "Disable",
        account_activity: "Account Activity",
        last_login: "Last Login",
        last_password_change: "Last Password Change",
        devices: "Devices",
        logout_all_devices: "Logout All Devices",
        delete_account: "Delete Account",
        delete_account_warning: "This action is irreversible. Your account and all data will be deleted.",
        confirm_delete_account: "Confirm Delete Account",
        bio: "Bio",
        fullName: "Full Name",
        passwordMismatch: "Passwords do not match",
        passwordLength: "Password must be at least 6 characters long",
        passwordChanged: "Password changed successfully",
        changePassword: "Change Password",

        // Schedule
        schedule: "Schedule",
        availability: "Availability",
        working_hours: "Working Hours",
        days_off: "Days Off",
        vacation: "Vacation",
        sick_leave: "Sick Leave",
        personal_leave: "Personal Leave",
        schedule_settings: "Schedule Settings",
        auto_schedule: "Auto Schedule",
        manual_schedule: "Manual Schedule",
        schedule_conflicts: "Schedule Conflicts",
        resolve_conflicts: "Resolve Conflicts",
        schedule_templates: "Schedule Templates",
        create_template: "Create Template",
        apply_template: "Apply Template",
        delete_template: "Delete Template",
        schedule_export: "Export Schedule",
        import_schedule: "Import Schedule",
        schedule_notifications: "Schedule Notifications",
        schedule_changes: "Schedule Changes",
        schedule_reminders: "Schedule Reminders",
        schedule_conflicts_resolved: "Schedule Conflicts Resolved",
        schedule_updated: "Schedule Updated",
        schedule_template_created: "Schedule Template Created",
        schedule_template_applied: "Schedule Template Applied",
        schedule_template_deleted: "Schedule Template Deleted",
        schedule_exported: "Schedule Exported",
        schedule_imported: "Schedule Imported",
        schedule_notification_sent: "Schedule Notification Sent",
        schedule_reminder_sent: "Schedule Reminder Sent",
        more: "more",
        no_tasks: "No Tasks",

        // Settings
        generalSettings: "General Settings",
        branchSettings: "Branch Settings",
        financialSettings: "Financial Settings",
        userSettings: "User Settings",
        notificationSettings: "Notification Settings",
        securitySettings: "Security Settings",
        systemSettings: "System Settings",
        backupSettings: "Backup Settings",
        integrationSettings: "Integration Settings",
        apiSettings: "API Settings",
        branchName: "Branch Name",
        taxRate: "Tax Rate",
        workingHours: "Working Hours",
        workingDays: "Working Days",
        website: "Website",

        // Reports
        financialReports: "Financial Reports",
        patientReports: "Patient Reports",
        staffReports: "Staff Reports",
        inventoryReports: "Inventory Reports",
        appointmentReports: "Appointment Reports",
        customReports: "Custom Reports",
        reportPeriod: "Report Period",
        daily: "Daily",
        weekly: "Weekly",
        monthly: "Monthly",
        quarterly: "Quarterly",
        yearly: "Yearly",
        customPeriod: "Custom Period",
        startDate: "Start Date",
        endDate: "End Date",
        generateReport: "Generate Report",
        exportReport: "Export Report",
        printReport: "Print Report",
        saveReport: "Save Report",
        reportGenerated: "Report Generated",
        reportExported: "Report Exported",
        reportPrinted: "Report Printed",
        reportSaved: "Report Saved",
        noReportData: "No Report Data",
        reportSettings: "Report Settings",
        reportTemplate: "Report Template",
        reportFormat: "Report Format",
        includeCharts: "Include Charts",
        includeTables: "Include Tables",
        includeSummary: "Include Summary",
        revenueReport: "Revenue Report",
        expenseReport: "Expense Report",
        profitReport: "Profit Report",
        taxReport: "Tax Report",
        patientVisitReport: "Patient Visit Report",
        staffPerformanceReport: "Staff Performance Report",
        inventoryUsageReport: "Inventory Usage Report",
        appointmentCompletionReport: "Appointment Completion Report",

        // Director Reports
        financial: "Financial",
        income: "Income",
        expense: "Expense",
        net_profit: "Net Profit",
        profitability: "Profitability",
        financial_indicators: "Financial Indicators",
        financial_report_details: "Financial Report Details",
        total_income: "Total Income",
        total_expenses: "Total Expenses",
        patient_dynamics: "Patient Dynamics",
        patient_report_details: "Patient Report Details",
        average_weekly: "Average Weekly",
        average_monthly: "Average Monthly",
        average_quarterly: "Average Quarterly",
        average_weekly_patients: "Average Weekly Patients:",
        average_monthly_patients: "Average Monthly Patients:",
        average_quarterly_patients: "Average Quarterly Patients:",
        growth: "Growth",
        doctor_efficiency: "Doctor Efficiency",
        top_performing_doctor: "Top Performing Doctor",
        average_patients_per_doctor: "Average Patients per Doctor",
        staff_performance_report: "Staff Performance Report",
        period: "Period",
        month: "Month",
        quarter: "Quarter",
        year: "Year",
        week1: "Week 1",
        week2: "Week 2",
        week3: "Week 3",
        week4: "Week 4",
        january: "January",
        february: "February",
        march: "March",
        quarter1: "Quarter 1",
        quarter2: "Quarter 2",
        quarter3: "Quarter 3",
        quarter4: "Quarter 4",
        history: "History",
        withdraw_cash: "Withdraw Cash",
        download_report_function: "Download Report Function",
        withdrawal_success: "Cash withdrawal successful",
        expense_history: "Expense History",
        category: "Category",
        amount: "Amount",
        description: "Description",
        enter_amount: "Enter amount",
        select_reason: "Select reason",
        enter_additional_description: "Enter additional description",
        confirm: "Confirm",

        // Withdrawal reasons
        salary: "Salary for doctors",
        salary_increase: "Additional salary for doctors",
        utilities: "Utility payments",
        rent: "Rent payment",
        supplies: "Medical supplies purchase",
        medicine: "Medicine purchase",
        repairs: "Repair works",
        marketing: "Marketing expenses",
        taxes: "Taxes",
        other_expenses: "Other expenses",
        other: "Other",

        // Withdrawal descriptions
        salary_payment_description: "Monthly salary payment for doctors",
        utilities_payment_description: "Electricity and water payments",
        supplies_payment_description: "Purchase of new medical equipment",
        medicine_payment_description: "Purchase of medicines",
        salary_increase_description: "Additional salary for Dr. Aziz Karimov",
        rent_payment_description: "Monthly rent payment",

        // Inpatient Rooms
        inpatient_rooms: "Inpatient Rooms",
        current_rooms: "Current Rooms",
        room_history: "Room History",
        add_new_room: "Add New Room",
        edit_room: "Edit Room",
        confirm_delete_room: "Are you sure you want to delete this room?",
        room_number: "Room Number",
        room_type: "Room Type",
        standard_room: "Standard Room",
        premium_room: "Premium Room",
        intensive_care: "Intensive Care",
        daily_rate: "Daily Rate",
        available: "Available",
        occupied: "Occupied",
        maintenance: "Maintenance",
        room: "Room",
        type: "Type",
        capacity: "Capacity",
        description: "Description",
        current_patients: "Current Patients",
        no_patients_in_room: "No patients in this room",
        assign_patient: "Assign Patient",
        assign_patient_to_room: "Assign Patient to Room",
        admission_date: "Admission Date",
        expected_discharge_date: "Expected Discharge Date",
        expected_discharge: "Expected Discharge",
        remaining_days: "Remaining Days",
        discharge: "Discharge",
        confirm_discharge_patient: "Are you sure you want to discharge this patient?",
        add_payment: "Add Payment",
        add_payment_for: "Add Payment for",
        payment_method: "Payment Method",
        payment_date: "Payment Date",
        total_payment: "Total Payment",
        room_occupancy_history: "Room Occupancy History",
        discharge_date: "Discharge Date",
        duration: "Duration",
        days: "days",
        no_room_history: "No room history",
        inpatient_rooms_statistics: "Inpatient Rooms Statistics",
        total_rooms: "Total Rooms",
        available_rooms: "Available Rooms",
        occupied_rooms: "Occupied Rooms",
        maintenance_rooms: "Maintenance Rooms",
        total_inpatients: "Total Inpatients",
        average_stay_duration: "Average Stay Duration",
        occupancy_rate: "Occupancy Rate",
        total_revenue: "Total Revenue",
        average_daily_revenue: "Average Daily Revenue",
        close: "Close",
        search_rooms_patients: "Search rooms and patients...",
        all_rooms: "All Rooms",
        select_nurse: "Select Nurse",
        morning_shift: "Morning Shift",
        evening_shift: "Evening Shift",
        night_shift: "Night Shift",
        critical: "Critical",
        stable: "Stable",
        improving: "Improving",

        // Tasks
        tasks_management: "Tasks Management",
        calendar_view: "Calendar View",
        list_view: "List View",
        add_task: "Add Task",
        search_tasks: "Search Tasks",
        no_tasks_found: "No Tasks Found",
        task_title: "Task Title",
        start_time: "Start Time",
        end_time: "End Time",
        select_assignee: "Select Assignee",
        create_task: "Create Task",
        update_task: "Update Task",
        mark_complete: "Mark Complete",
        start_task: "Start Task",
        reopen_task: "Reopen Task",
        task_details: "Task Details",
        no_description: "No Description",
        please_select_assignee: "Please select assignee",
    },
}

// Create language context
const LanguageContext = createContext()

// Language provider component
export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState("uz")

    // Load saved language preference from localStorage on component mount
    useEffect(() => {
        const savedLanguage = localStorage.getItem("language")
        if (savedLanguage && languages[savedLanguage]) {
            setLanguage(savedLanguage)
        }
    }, [])

    // Save language preference to localStorage when it changes
    useEffect(() => {
        localStorage.setItem("language", language)
    }, [language])

    // Function to change language
    const changeLanguage = (lang) => {
        if (languages[lang]) {
            setLanguage(lang)
        }
    }

    // Get translation for a key
    const t = (key) => {
        if (translations[language] && translations[language][key]) {
            return translations[language][key]
        }
        // Fallback to English if translation not found
        if (translations.en && translations.en[key]) {
            return translations.en[key]
        }
        // Return the key itself if no translation found
        return key
    }

    return (
        <LanguageContext.Provider value={{ language, languages, changeLanguage, t }}>{children}</LanguageContext.Provider>
    )
}

// Custom hook to use language context
export const useLanguage = () => {
    const context = useContext(LanguageContext)
    if (!context) {
        throw new Error("useLanguage must be used within a LanguageProvider")
    }
    return context
}

export default LanguageContext
