"use client"
import { createContext, useState, useContext, useEffect } from "react"

// Available languages
const languages = {
    uz: "O'zbek",
    ru: "Русский",
    en: "English",
    kz: "Қазақша",
    zh: "中文",
}

// Translations
const translations = {
    uz: {
        // Auth
        login: "Kirish",
        signup: "Ro'yxatdan o'tish",
        logout: "Chiqish",
        email: "Email",
        password: "Parol",
        confirm_password: "Parolni tasdiqlang",
        forgot_password: "Parolni unutdingizmi?",
        remember_me: "Meni eslab qol",
        request_access: "Kirish huquqini so'rash",
        loggingIn: "Kirish...",
        or: "yoki",
        noAccount: "Hisobingiz yo'qmi?",
        signUp: "Ro'yxatdan o'ting",
        requestReceived: "So'rovingiz qabul qilindi",
        credentialsSentTo: "Login va parol ma'lumotlari quyidagi elektron pochtaga yuboriladi:",
        backToLogin: "Loginni qaytish",
        loginInstructions: "Tizimga kirish uchun ma'lumotlaringizni kiriting",
        emailPasswordRequired: "Email va parol kiritilishi shart",
        loginFailed: "Kirish muvaffaqiyatsiz bo'ldi",
        clinicName: "Klinika nomi",
        enterClinicInfo: "Klinika ma'lumotlarini kiriting",
        submit: "Yuborish",
        back: "Orqaga",

        // Roles
        director: "Direktor",
        admin: "Administrator",
        doctor: "Shifokor",
        user: "Foydalanuvchi",

        // Dashboard
        dashboard: "Dashboard",
        staff: "Xodimlar",
        cabinets: "Kabinetlar",
        patients: "Bemorlar",
        appointments: "Qabullar",
        reports: "Hisobotlar",
        settings: "Sozlamalar",
        notifications: "Xabarnomalar",
        profile: "Profil",
        loading: "Yuklanmoqda",
        allBranches: "Barcha filiallar",

        // Common
        search: "Qidirish...",
        filters: "Filtrlar",
        all: "Barchasi",
        active: "Faol",
        inactive: "Nofaol",
        add: "Qo'shish",
        save: "Saqlash",
        cancel: "Bekor qilish",
        edit: "Tahrirlash",
        delete: "O'chirish",
        actions: "Amallar",
        name: "Ism",
        status: "Holat",
        branch: "Filial",
        branch1: "1-Filial",
        branch2: "2-Filial",
        branch3: "3-Filial",
        no_data_found: "Ma'lumot topilmadi",
        statistics: "Statistika",
        close_stats: "Statistikani yopish",
        today: "Bugun",
        yesterday: "Kecha",
        daysAgo: "kun oldin",
        markAllAsRead: "Hammasini o'qilgan deb belgilash",
        markAsRead: "O'qilgan deb belgilash",
        read: "O'qilgan",
        unread: "O'qilmagan",
        siteNews: "Sayt yangiliklari",
        workNotifications: "Ish xabarlari",
        noNotifications: "Xabarnomalar yo'q",
        high: "Yuqori",
        medium: "O'rta",
        low: "Past",
        priority: "Muhimlik",
        settingsSaved: "Sozlamalar saqlandi",
        guest: "Mehmon",

        // Staff
        add_new_staff: "Yangi xodim qo'shish",
        edit_staff: "Xodimni tahrirlash",
        confirm_delete_staff: "Rostdan ham bu xodimni o'chirmoqchimisiz?",
        position: "Lavozim",
        department: "Bo'lim",
        phone: "Telefon",
        monthly_salary: "Oylik maosh",
        vacation_status: "Ta'til holati",
        on_vacation: "Ta'tilda",
        at_work: "Ishda",
        vacation_period: "Ta'til muddati",
        vacation_period_example: "Misol: 2023-05-20 - 2023-06-05",
        full_name: "To'liq ism",
        total_staff: "Jami xodimlar",
        active_staff: "Faol xodimlar",
        staff_on_vacation: "Ta'tildagi xodimlar",
        total_salary: "Jami oylik maosh",
        role_distribution: "Lavozimlar bo'yicha taqsimot",
        currency: "so'm",
        inactive_staff: "Nofaol xodimlar",

        // Staff positions
        doctor: "Shifokor",
        admin: "Admin",
        nurse: "Hamshira",
        lab_technician: "Laborant",
        pharmacist: "Farmatsevt",
        receptionist: "Qabulxona xodimi",
        accountant: "Hisobchi",
        cleaner: "Tozalovchi",
        security: "Qo'riqchi",
        buyer: "Xarid bo'yicha mutaxassis",
        manager: "Menejer",

        // Cabinets
        add_new_cabinet: "Yangi kabinet qo'shish",
        edit_cabinet: "Kabinetni tahrirlash",
        confirm_delete_cabinet: "Rostdan ham bu kabinetni o'chirmoqchimisiz?",
        cabinet_number: "Kabinet raqami",
        cabinet_name: "Kabinet nomi",
        floor: "Qavat",
        capacity: "Sig'imi",
        doctors_count: "shifokorlar soni",
        maintenance: "Ta'mirda",
        total_cabinets: "Jami kabinetlar",
        active_cabinets: "Faol kabinetlar",
        maintenance_cabinets: "Ta'mirdagi kabinetlar",
        total_capacity: "Jami sig'im",
        floor_distribution: "Qavatlar bo'yicha taqsimot",
        number: "Raqam",
        inactive_cabinets: "Nofaol kabinetlar",

        // Patients
        add_new_patient: "Yangi bemor qo'shish",
        edit_patient: "Bemorni tahrirlash",
        confirm_delete_patient: "Rostdan ham bu bemorni o'chirmoqchimisiz?",
        age: "Yosh",
        gender: "Jins",
        male: "Erkak",
        female: "Ayol",
        address: "Manzil",
        diagnosis: "Tashxis",
        doctor: "Shifokor",
        last_visit: "Oxirgi tashrif",
        export_to_pdf: "PDF formatida yuklab olish",
        export_to_excel: "Excel formatida yuklab olish",
        blood_group: "Qon guruhi",
        insurance: "Sug'urta",
        emergency_contact: "Favqulodda aloqa",
        allergies: "Allergiyalar",
        medical_history: "Tibbiy tarix",
        patient_id: "Bemor ID",
        registration_date: "Ro'yxatga olingan sana",
        patient_details: "Bemor tafsilotlari",
        patient_list: "Bemorlar ro'yxati",
        patient_statistics: "Bemorlar statistikasi",
        total_patients: "Jami bemorlar",
        new_patients: "Yangi bemorlar",
        returning_patients: "Qaytgan bemorlar",
        patient_demographics: "Bemorlar demografiyasi",
        age_distribution: "Yosh bo'yicha taqsimot",
        gender_distribution: "Jins bo'yicha taqsimot",
        visit_history: "Tashrif tarixi",
        upcoming_appointments: "Kelgusi qabullar",
        treatment_plan: "Davolash rejasi",
        prescriptions: "Retseptlar",
        lab_results: "Laboratoriya natijalari",
        billing_info: "To'lov ma'lumotlari",
        insurance_details: "Sug'urta tafsilotlari",
        insurance_provider: "Sug'urta provayderi",
        policy_number: "Polis raqami",
        coverage_details: "Qamrov tafsilotlari",
        patient_notes: "Bemor qaydlari",
        add_note: "Qayd qo'shish",
        upload_documents: "Hujjatlarni yuklash",
        download_report: "Hisobotni yuklab olish",
        print_details: "Tafsilotlarni chop etish",
        share_records: "Yozuvlarni ulashish",
        filter_by_doctor: "Shifokor bo'yicha filtrlash",
        filter_by_date: "Sana bo'yicha filtrlash",
        filter_by_status: "Holat bo'yicha filtrlash",
        sort_by_name: "Ism bo'yicha saralash",
        sort_by_date: "Sana bo'yicha saralash",
        sort_by_id: "ID bo'yicha saralash",
        inactive_patients: "Nofaol bemorlar",
        patients_count: "Bemorlar soni",

        // Appointments
        add_new_appointment: "Yangi qabul qo'shish",
        edit_appointment: "Qabulni tahrirlash",
        confirm_delete_appointment: "Rostdan ham bu qabulni o'chirmoqchimisiz?",
        patient: "Bemor",
        date: "Sana",
        time: "Vaqt",
        notes: "Izohlar",
        pending: "Kutilmoqda",
        confirmed: "Tasdiqlangan",
        completed: "Yakunlangan",
        cancelled: "Bekor qilingan",
        select_patient: "Bemorni tanlang",
        select_doctor: "Shifokorni tanlang",
        appointment_details: "Qabul tafsilotlari",
        appointment_history: "Qabul tarixi",
        upcoming_appointments: "Kelgusi qabullar",
        past_appointments: "O'tgan qabullar",
        appointment_status: "Qabul holati",
        reschedule: "Qayta rejalashtirish",
        cancel_appointment: "Qabulni bekor qilish",
        appointment_type: "Qabul turi",
        duration: "Davomiyligi",
        reason: "Sabab",
        symptoms: "Alomatlar",
        appointment_notes: "Qabul qaydlari",
        follow_up: "Keyingi qabul",
        appointment_reminder: "Qabul eslatmasi",
        send_reminder: "Eslatma yuborish",
        reminder_sent: "Eslatma yuborildi",
        appointment_fee: "Qabul to'lovi",
        payment_status: "To'lov holati",
        paid: "To'langan",
        unpaid: "To'lanmagan",
        partial: "Qisman to'langan",
        payment_method: "To'lov usuli",
        cash: "Naqd pul",
        card: "Karta",
        insurance: "Sug'urta",
        appointment_location: "Qabul joyi",
        online: "Onlayn",
        in_person: "Shaxsan",
        appointment_documents: "Qabul hujjatlari",
        upload_documents: "Hujjatlarni yuklash",
        download_documents: "Hujjatlarni yuklab olish",
        appointment_history_empty: "Qabul tarixi bo'sh",
        no_upcoming_appointments: "Kelgusi qabullar yo'q",
        no_past_appointments: "O'tgan qabullar yo'q",
        appointment_created: "Qabul yaratildi",
        appointment_updated: "Qabul yangilandi",
        appointment_deleted: "Qabul o'chirildi",
        appointment_confirmed: "Qabul tasdiqlandi",
        appointment_completed: "Qabul yakunlandi",
        appointment_cancelled: "Qabul bekor qilindi",
        appointment_rescheduled: "Qabul qayta rejalashtirildi",

        // Profile
        personal_info: "Shaxsiy ma'lumotlar",
        change_password: "Parolni o'zgartirish",
        language: "Til",
        save_changes: "O'zgarishlarni saqlash",
        current_password: "Joriy parol",
        new_password: "Yangi parol",
        confirm_new_password: "Yangi parolni tasdiqlang",
        profile_updated: "Profil yangilandi",
        password_changed: "Parol o'zgartirildi",
        passwords_do_not_match: "Parollar mos kelmadi",
        current_password_incorrect: "Joriy parol noto'g'ri",
        profile_picture: "Profil rasmi",
        upload_picture: "Rasm yuklash",
        remove_picture: "Rasmni o'chirish",
        account_settings: "Hisob sozlamalari",
        notification_settings: "Xabarnoma sozlamalari",
        email_notifications: "Email xabarnomalar",
        sms_notifications: "SMS xabarnomalar",
        app_notifications: "Ilova xabarnomalar",
        account_security: "Hisob xavfsizligi",
        two_factor_authentication: "Ikki faktorli autentifikatsiya",
        enable: "Yoqish",
        disable: "O'chirish",
        account_activity: "Hisob faoliyati",
        last_login: "Oxirgi kirish",
        last_password_change: "Oxirgi parol o'zgarishi",
        devices: "Qurilmalar",
        logout_all_devices: "Barcha qurilmalardan chiqish",
        delete_account: "Hisobni o'chirish",
        delete_account_warning: "Bu amal qaytarib bo'lmaydi. Hisobingiz va barcha ma'lumotlaringiz o'chiriladi.",
        confirm_delete_account: "Hisobni o'chirishni tasdiqlang",

        // Schedule
        schedule: "Jadval",
        availability: "Bandlik",
        working_hours: "Ish soatlari",
        days_off: "Dam olish kunlari",
        vacation: "Ta'til",
        sick_leave: "Kasallik ta'tili",
        personal_leave: "Shaxsiy ta'til",
        schedule_settings: "Jadval sozlamalari",
        auto_schedule: "Avtomatik jadval",
        manual_schedule: "Qo'lda jadval",
        schedule_conflicts: "Jadval ziddiyatlari",
        resolve_conflicts: "Ziddiyatlarni hal qilish",
        schedule_templates: "Jadval shablonlari",
        create_template: "Shablon yaratish",
        apply_template: "Shablonni qo'llash",
        delete_template: "Shablonni o'chirish",
        schedule_export: "Jadvalni eksport qilish",
        import_schedule: "Jadvalni import qilish",
        schedule_notifications: "Jadval xabarnomalar",
        schedule_changes: "Jadval o'zgarishlari",
        schedule_reminders: "Jadval eslatmalari",
        schedule_conflicts_resolved: "Jadval ziddiyatlari hal qilindi",
        schedule_updated: "Jadval yangilandi",
        schedule_template_created: "Jadval shabloni yaratildi",
        schedule_template_applied: "Jadval shabloni qo'llanildi",
        schedule_template_deleted: "Jadval shabloni o'chirildi",
        schedule_exported: "Jadval eksport qilindi",
        schedule_imported: "Jadval import qilindi",
        schedule_notification_sent: "Jadval xabarnomasi yuborildi",
        schedule_reminder_sent: "Jadval eslatmasi yuborildi",

        // Settings
        generalSettings: "Umumiy sozlamalar",
        branchSettings: "Filial sozlamalari",
        financialSettings: "Moliyaviy sozlamalar",
        userSettings: "Foydalanuvchi sozlamalari",
        notificationSettings: "Xabarnoma sozlamalari",
        securitySettings: "Xavfsizlik sozlamalari",
        systemSettings: "Tizim sozlamalari",
        backupSettings: "Zaxira sozlamalari",
        integrationSettings: "Integratsiya sozlamalari",
        apiSettings: "API sozlamalari",
        branchName: "Filial nomi",
        taxRate: "Soliq stavkasi",
        workingHours: "Ish soatlari",
        workingDays: "Ish kunlari",
        website: "Veb-sayt",

        // Reports
        financialReports: "Moliyaviy hisobotlar",
        patientReports: "Bemor hisobotlari",
        staffReports: "Xodim hisobotlari",
        inventoryReports: "Inventar hisobotlari",
        appointmentReports: "Qabul hisobotlari",
        customReports: "Maxsus hisobotlar",
        reportPeriod: "Hisobot davri",
        daily: "Kunlik",
        weekly: "Haftalik",
        monthly: "Oylik",
        quarterly: "Choraklik",
        yearly: "Yillik",
        customPeriod: "Maxsus davr",
        startDate: "Boshlanish sanasi",
        endDate: "Tugash sanasi",
        generateReport: "Hisobot yaratish",
        exportReport: "Hisobotni eksport qilish",
        printReport: "Hisobotni chop etish",
        saveReport: "Hisobotni saqlash",
        reportGenerated: "Hisobot yaratildi",
        reportExported: "Hisobot eksport qilindi",
        reportPrinted: "Hisobot chop etildi",
        reportSaved: "Hisobot saqlandi",
        noReportData: "Hisobot ma'lumotlari yo'q",
        reportSettings: "Hisobot sozlamalari",
        reportTemplate: "Hisobot shabloni",
        reportFormat: "Hisobot formati",
        includeCharts: "Diagrammalarni qo'shish",
        includeTables: "Jadvallarni qo'shish",
        includeSummary: "Xulosani qo'shish",
        revenueReport: "Daromad hisoboti",
        expenseReport: "Xarajat hisoboti",
        profitReport: "Foyda hisoboti",
        taxReport: "Soliq hisoboti",
        patientVisitReport: "Bemor tashrifi hisoboti",
        staffPerformanceReport: "Xodim samaradorligi hisoboti",
        inventoryUsageReport: "Inventar foydalanish hisoboti",
        appointmentCompletionReport: "Qabul yakunlash hisoboti",

        // Director Reports
        financial: "Moliyaviy",
        income: "Daromad",
        expense: "Xarajat",
        net_profit: "Sof foyda",
        profitability: "Rentabellik",
        financial_indicators: "Moliyaviy ko'rsatkichlar",
        financial_report_details: "Moliyaviy hisobot tafsilotlari",
        total_income: "Jami daromad",
        total_expenses: "Jami xarajat",
        patient_dynamics: "Bemorlar dinamikasi",
        patient_report_details: "Bemorlar hisoboti tafsilotlari",
        average_weekly: "O'rtacha haftalik",
        average_monthly: "O'rtacha oylik",
        average_quarterly: "O'rtacha choraklik",
        average_weekly_patients: "O'rtacha haftalik bemorlar:",
        average_monthly_patients: "O'rtacha oylik bemorlar:",
        average_quarterly_patients: "O'rtacha choraklik bemorlar:",
        growth: "O'sish",
        doctor_efficiency: "Shifokorlar samaradorligi",
        top_performing_doctor: "Eng samarali shifokor",
        average_patients_per_doctor: "O'rtacha bemor soni",
        staff_performance_report: "Xodimlar samaradorligi hisoboti",
        period: "Davr",
        month: "Oy",
        quarter: "Chorak",
        year: "Yil",
        week1: "1-hafta",
        week2: "2-hafta",
        week3: "3-hafta",
        week4: "4-hafta",
        january: "Yanvar",
        february: "Fevral",
        march: "Mart",
        quarter1: "1-chorak",
        quarter2: "2-chorak",
        quarter3: "3-chorak",
        quarter4: "4-chorak",
        history: "Tarix",
        withdraw_cash: "Kassadan pul olish",
        download_report_function: "Hisobot yuklab olish funksiyasi",
        withdrawal_success: "Kassadan pul olish muvaffaqiyatli amalga oshirildi",
        expense_history: "Xarajatlar tarixi",
        category: "Kategoriya",
        amount: "Summa",
        description: "Izoh",
        enter_amount: "Summani kiriting",
        select_reason: "Sababni tanlang",
        enter_additional_description: "Qo'shimcha izoh kiriting",
        confirm: "Tasdiqlash",

        // Withdrawal reasons
        salary: "Shifokorlarga oylik",
        salary_increase: "Shifokorlarga qo'shimcha oylik",
        utilities: "Kommunal to'lovlar",
        rent: "Ijara to'lovi",
        supplies: "Tibbiy jihozlar xaridi",
        medicine: "Dori-darmonlar xaridi",
        repairs: "Ta'mirlash ishlari",
        marketing: "Marketing xarajatlari",
        taxes: "Soliqlar",
        other_expenses: "Boshqa xarajatlar",
        other: "Boshqa",

        // Withdrawal descriptions
        salary_payment_description: "Shifokorlarga oylik maosh to'lovi",
        utilities_payment_description: "Elektr va suv to'lovlari",
        supplies_payment_description: "Yangi tibbiy jihozlar xaridi",
        medicine_payment_description: "Dori-darmonlar xaridi",
        salary_increase_description: "Dr. Aziz Karimovga qo'shimcha oylik",
        rent_payment_description: "Oylik ijara to'lovi",
        all_branches: "Barcha filiallar",

        // Inpatient Rooms
        inpatient_rooms: "Yotib davolanish xonalari",
        current_rooms: "Joriy xonalar",
        room_history: "Xonalar tarixi",
        add_new_room: "Yangi xona qo'shish",
        edit_room: "Xonani tahrirlash",
        confirm_delete_room: "Rostdan ham bu xonani o'chirmoqchimisiz?",
        room_number: "Xona raqami",
        room_type: "Xona turi",
        standard_room: "Standart xona",
        premium_room: "Premium xona",
        intensive_care: "Intensiv terapiya",
        daily_rate: "Kunlik narx",
        available: "Bo'sh",
        occupied: "Band",
        maintenance: "Ta'mirda",
        room: "Xona",
        type: "Turi",
        capacity: "Sig'imi",
        description: "Tavsif",
        current_patients: "Joriy bemorlar",
        no_patients_in_room: "Bu xonada bemorlar yo'q",
        assign_patient: "Bemorni tayinlash",
        assign_patient_to_room: "Bemorni xonaga tayinlash",
        admission_date: "Qabul qilingan sana",
        expected_discharge_date: "Kutilayotgan chiqish sanasi",
        expected_discharge: "Kutilayotgan chiqish",
        remaining_days: "Qolgan kunlar",
        discharge: "Chiqarish",
        confirm_discharge_patient: "Rostdan ham bu bemorni chiqarmoqchimisiz?",
        add_payment: "To'lov qo'shish",
        add_payment_for: "Uchun to'lov qo'shish",
        payment_method: "To'lov usuli",
        payment_date: "To'lov sanasi",
        total_payment: "Jami to'lov",
        room_occupancy_history: "Xona band bo'lish tarixi",
        discharge_date: "Chiqarilgan sana",
        duration: "Davomiyligi",
        days: "kun",
        no_room_history: "Xona tarixi yo'q",
        inpatient_rooms_statistics: "Yotib davolanish xonalari statistikasi",
        total_rooms: "Jami xonalar",
        available_rooms: "Bo'sh xonalar",
        occupied_rooms: "Band xonalar",
        maintenance_rooms: "Ta'mirdagi xonalar",
        total_inpatients: "Jami yotib davolanuvchilar",
        average_stay_duration: "O'rtacha qolish davomiyligi",
        occupancy_rate: "Band bo'lish darajasi",
        total_revenue: "Jami daromad",
        average_daily_revenue: "O'rtacha kunlik daromad",
        close: "Yopish",
        search_rooms_patients: "Xonalar va bemorlarni qidirish...",
        all_rooms: "Barcha xonalar",
        select_nurse: "Hamshirani tanlang",
        morning_shift: "Ertalabki smena",
        evening_shift: "Kechki smena",
        night_shift: "Tungi smena",
        critical: "Og'ir ahvolda",
        recovering: "Tuzalmoqda",
        active: "Faol",
    },
    ru: {
        // Auth
        login: "Вход",
        signup: "Регистрация",
        logout: "Выход",
        email: "Email",
        password: "Пароль",
        confirm_password: "Подтвердите пароль",
        forgot_password: "Забыли пароль?",
        remember_me: "Запомнить меня",
        request_access: "Запросить доступ",
        loggingIn: "Вход...",
        or: "или",
        noAccount: "Нет аккаунта?",
        signUp: "Зарегистрироваться",
        requestReceived: "Ваш запрос получен",
        credentialsSentTo: "Данные для входа будут отправлены на:",
        backToLogin: "Вернуться к входу",
        loginInstructions: "Введите данные для входа в систему",
        emailPasswordRequired: "Требуется ввести email и пароль",
        loginFailed: "Не удалось войти",
        clinicName: "Название клиники",
        enterClinicInfo: "Введите информацию о клинике",
        submit: "Отправить",
        back: "Назад",

        // Roles
        director: "Директор",
        admin: "Администратор",
        doctor: "Врач",
        user: "Пользователь",

        // Dashboard
        dashboard: "Панель управления",
        staff: "Персонал",
        cabinets: "Кабинеты",
        patients: "Пациенты",
        appointments: "Приемы",
        reports: "Отчеты",
        settings: "Настройки",
        notifications: "Уведомления",
        profile: "Профиль",
        loading: "Загрузка",
        allBranches: "Все филиалы",

        // Common
        search: "Поиск...",
        filters: "Фильтры",
        all: "Все",
        active: "Активный",
        inactive: "Неактивный",
        add: "Добавить",
        save: "Сохранить",
        cancel: "Отмена",
        edit: "Редактировать",
        delete: "Удалить",
        actions: "Действия",
        name: "Имя",
        status: "Статус",
        branch: "Филиал",
        branch1: "Филиал 1",
        branch2: "Филиал 2",
        branch3: "Филиал 3",
        no_data_found: "Данные не найдены",
        statistics: "Статистика",
        close_stats: "Закрыть статистику",
        today: "Сегодня",
        yesterday: "Вчера",
        daysAgo: "дней назад",
        markAllAsRead: "Отметить все как прочитанные",
        markAsRead: "Отметить как прочитанное",
        read: "Прочитано",
        unread: "Непрочитано",
        siteNews: "Новости сайта",
        workNotifications: "Рабочие уведомления",
        noNotifications: "Нет уведомлений",
        high: "Высокий",
        medium: "Средний",
        low: "Низкий",
        priority: "Приоритет",
        settingsSaved: "Настройки сохранены",
        guest: "Гость",

        // Staff
        add_new_staff: "Добавить нового сотрудника",
        edit_staff: "Редактировать сотрудника",
        confirm_delete_staff: "Вы действительно хотите удалить этого сотрудника?",
        position: "Должность",
        department: "Отдел",
        phone: "Телефон",
        monthly_salary: "Ежемесячная зарплата",
        vacation_status: "Статус отпуска",
        on_vacation: "В отпуске",
        at_work: "На работе",
        vacation_period: "Период отпуска",
        vacation_period_example: "Пример: 2023-05-20 - 2023-06-05",
        full_name: "Полное имя",
        total_staff: "Всего сотрудников",
        active_staff: "Активные сотрудники",
        staff_on_vacation: "Сотрудники в отпуске",
        total_salary: "Общая зарплата",
        role_distribution: "Распределение по должностям",
        currency: "сум",
        inactive_staff: "Неактивные сотрудники",

        // Staff positions
        doctor: "Врач",
        admin: "Администратор",
        nurse: "Медсестра",
        lab_technician: "Лаборант",
        pharmacist: "Фармацевт",
        receptionist: "Регистратор",
        accountant: "Бухгалтер",
        cleaner: "Уборщик",
        security: "Охранник",
        buyer: "Специалист по закупкам",
        manager: "Менеджер",

        // Cabinets
        add_new_cabinet: "Добавить новый кабинет",
        edit_cabinet: "Редактировать кабинет",
        confirm_delete_cabinet: "Вы действительно хотите удалить этот кабинет?",
        cabinet_number: "Номер кабинета",
        cabinet_name: "Название кабинета",
        floor: "Этаж",
        capacity: "Вместимость",
        doctors_count: "количество врачей",
        maintenance: "На ремонте",
        total_cabinets: "Всего кабинетов",
        active_cabinets: "Активные кабинеты",
        maintenance_cabinets: "Кабинеты на ремонте",
        total_capacity: "Общая вместимость",
        floor_distribution: "Распределение по этажам",
        number: "Номер",
        inactive_cabinets: "Неактивные кабинеты",

        // Patients
        add_new_patient: "Добавить нового пациента",
        edit_patient: "Редактировать пациента",
        confirm_delete_patient: "Вы действительно хотите удалить этого пациента?",
        age: "Возра��т",
        gender: "Пол",
        male: "Мужской",
        female: "Женский",
        address: "Адрес",
        diagnosis: "Диагноз",
        doctor: "Врач",
        last_visit: "Последний визит",
        export_to_pdf: "Скачать в формате PDF",
        export_to_excel: "Скачать в формате Excel",
        blood_group: "Группа крови",
        insurance: "Страховка",
        emergency_contact: "Экстренный контакт",
        allergies: "Аллергии",
        medical_history: "История болезни",
        patient_id: "ID пациента",
        registration_date: "Дата регистрации",
        patient_details: "Детали пациента",
        patient_list: "Список пациентов",
        patient_statistics: "Статистика пациентов",
        total_patients: "Всего пациентов",
        new_patients: "Новые пациенты",
        returning_patients: "Вернувшиеся пациенты",
        patient_demographics: "Демография пациентов",
        age_distribution: "Распределение по возрасту",
        gender_distribution: "Распределение по полу",
        visit_history: "История посещений",
        upcoming_appointments: "Предстоящие приемы",
        treatment_plan: "План лечения",
        prescriptions: "Рецепты",
        lab_results: "Результаты анализов",
        billing_info: "Платежная информация",
        insurance_details: "Детали страховки",
        insurance_provider: "Страховая компания",
        policy_number: "Номер полиса",
        coverage_details: "Детали покрытия",
        patient_notes: "Заметки о пациенте",
        add_note: "Добавить заметку",
        upload_documents: "Загрузить документы",
        download_report: "Скачать отчет",
        print_details: "Распечатать детали",
        share_records: "Поделиться записями",
        filter_by_doctor: "Фильтр по врачу",
        filter_by_date: "Фильтр по дате",
        filter_by_status: "Фильтр по статусу",
        sort_by_name: "Сортировать по имени",
        sort_by_date: "Сортировать по дате",
        sort_by_id: "Сортировать по ID",
        inactive_patients: "Неактивные пациенты",
        patients_count: "Количество пациентов",

        // Appointments
        add_new_appointment: "Добавить новый прием",
        edit_appointment: "Редактировать прием",
        confirm_delete_appointment: "Вы действительно хотите удалить этот прием?",
        patient: "Пациент",
        date: "Дата",
        time: "Время",
        notes: "Примечания",
        pending: "Ожидается",
        confirmed: "Подтвержден",
        completed: "Завершен",
        cancelled: "Отменен",
        select_patient: "Выберите пациента",
        select_doctor: "Выберите врача",
        appointment_details: "Детали приема",
        appointment_history: "История приемов",
        upcoming_appointments: "Предстоящие приемы",
        past_appointments: "Прошедшие приемы",
        appointment_status: "Статус приема",
        reschedule: "Перенести",
        cancel_appointment: "Отменить прием",
        appointment_type: "Тип приема",
        duration: "Продолжительность",
        reason: "Причина",
        symptoms: "Симптомы",
        appointment_notes: "Заметки о приеме",
        follow_up: "Последующий прием",
        appointment_reminder: "Напоминание о приеме",
        send_reminder: "Отправить напоминание",
        reminder_sent: "Напоминание отправлено",
        appointment_fee: "Стоимость приема",
        payment_status: "Статус оплаты",
        paid: "Оплачено",
        unpaid: "Не оплачено",
        partial: "Частично оплачено",
        payment_method: "Способ оплаты",
        cash: "Наличные",
        card: "Карта",
        insurance: "Страховка",
        appointment_location: "Место приема",
        online: "Онлайн",
        in_person: "Лично",
        appointment_documents: "Документы приема",
        upload_documents: "Загрузить документы",
        download_documents: "Скачать документы",
        appointment_history_empty: "История приемов пуста",
        no_upcoming_appointments: "Нет предстоящих приемов",
        no_past_appointments: "Нет прошедших приемов",
        appointment_created: "Прием создан",
        appointment_updated: "Прием обновлен",
        appointment_deleted: "Прием удален",
        appointment_confirmed: "Прием подтвержден",
        appointment_completed: "Прием завершен",
        appointment_cancelled: "Прием отменен",
        appointment_rescheduled: "Прием перенесен",

        // Profile
        personal_info: "Личная информация",
        change_password: "Изменить пароль",
        language: "Язык",
        save_changes: "Сохранить изменения",
        current_password: "Текущий пароль",
        new_password: "Новый пароль",
        confirm_new_password: "Подтвердите новый пароль",
        profile_updated: "Профиль обновлен",
        password_changed: "Пароль изменен",
        passwords_do_not_match: "Пароли не совпадают",
        current_password_incorrect: "Текущий пароль неверен",
        profile_picture: "Изображение профиля",
        upload_picture: "Загрузить изображение",
        remove_picture: "Удалить изображение",
        account_settings: "Настройки аккаунта",
        notification_settings: "Настройки уведомлений",
        email_notifications: "Email уведомления",
        sms_notifications: "SMS уведомления",
        app_notifications: "Уведомления приложения",
        account_security: "Безопасность аккаунта",
        two_factor_authentication: "Двухфакторная аутентификация",
        enable: "Включить",
        disable: "Отключить",
        account_activity: "Активность аккаунта",
        last_login: "Последний вход",
        last_password_change: "Последнее изменение пароля",
        devices: "Устройства",
        logout_all_devices: "Выйти со всех устройств",
        delete_account: "Удалить аккаунт",
        delete_account_warning: "Это действие необратимо. Ваш аккаунт и все данные будут удалены.",
        confirm_delete_account: "Подтвердите удаление аккаунта",

        // Schedule
        schedule: "Расписание",
        availability: "Доступность",
        working_hours: "Рабочие часы",
        days_off: "Выходные дни",
        vacation: "Отпуск",
        sick_leave: "Больничный",
        personal_leave: "Личный отпуск",
        schedule_settings: "Настройки расписания",
        auto_schedule: "Автоматическое расписание",
        manual_schedule: "Ручное расписание",
        schedule_conflicts: "Конфликты расписания",
        resolve_conflicts: "Разрешить конфликты",
        schedule_templates: "Шаблоны расписания",
        create_template: "Создать шаблон",
        apply_template: "Применить шаблон",
        delete_template: "Удалить шаблон",
        schedule_export: "Экспорт расписания",
        import_schedule: "Импорт расписания",
        schedule_notifications: "Уведомления о расписании",
        schedule_changes: "Изменения в расписании",
        schedule_reminders: "Напоминания о расписании",
        schedule_conflicts_resolved: "Конфликты расписания разрешены",
        schedule_updated: "Расписание обновлено",
        schedule_template_created: "Шаблон расписания создан",
        schedule_template_applied: "Шаблон расписания применен",
        schedule_template_deleted: "Шаблон расписания удален",
        schedule_exported: "Расписание экспортировано",
        schedule_imported: "Расписание импортировано",
        schedule_notification_sent: "Уведомление о расписании отправлено",
        schedule_reminder_sent: "Напоминание о расписании отправлено",

        // Settings
        generalSettings: "Общие настройки",
        branchSettings: "Настройки филиалов",
        financialSettings: "Финансовые настройки",
        userSettings: "Настройки пользователя",
        notificationSettings: "Настройки уведомлений",
        securitySettings: "Настройки безопасности",
        systemSettings: "Системные настройки",
        backupSettings: "Настройки резервного копирования",
        integrationSettings: "Настройки интеграции",
        apiSettings: "Настройки API",
        branchName: "Название филиала",
        taxRate: "Налоговая ставка",
        workingHours: "Рабочие часы",
        workingDays: "Рабочие дни",
        website: "Веб-сайт",

        // Reports
        financialReports: "Финансовые отчеты",
        patientReports: "Отчеты по пациентам",
        staffReports: "Отчеты по персоналу",
        inventoryReports: "Отчеты по инвентарю",
        appointmentReports: "Отчеты по приемам",
        customReports: "Пользовательские отчеты",
        reportPeriod: "Период отчета",
        daily: "Ежедневно",
        weekly: "Еженедельно",
        monthly: "Ежемесячно",
        quarterly: "Ежеквартально",
        yearly: "Ежегодно",
        customPeriod: "Пользовательский период",
        startDate: "Дата начала",
        endDate: "Дата окончания",
        generateReport: "Сгенерировать отчет",
        exportReport: "Экспортировать отчет",
        printReport: "Распечатать отчет",
        saveReport: "Сохранить отчет",
        reportGenerated: "Отчет сгенерирован",
        reportExported: "Отчет экспортирован",
        reportPrinted: "Отчет распечатан",
        reportSaved: "Отчет сохранен",
        noReportData: "Нет данных для отчета",
        reportSettings: "Настройки отчета",
        reportTemplate: "Шаблон отчета",
        reportFormat: "Формат отчета",
        includeCharts: "Включить диаграммы",
        includeTables: "Включить таблицы",
        includeSummary: "Включить сводку",
        revenueReport: "Отчет о доходах",
        expenseReport: "Отчет о расходах",
        profitReport: "Отчет о прибыли",
        taxReport: "Налоговый отчет",
        patientVisitReport: "Отчет о посещениях пациентов",
        staffPerformanceReport: "Отчет о производительности персонала",
        inventoryUsageReport: "Отчет об использовании инвентаря",
        appointmentCompletionReport: "Отчет о завершении приемов",

        // Director Reports
        financial: "Финансовый",
        income: "Доход",
        expense: "Расход",
        net_profit: "Чистая прибыль",
        profitability: "Рентабельность",
        financial_indicators: "Финансовые показатели",
        financial_report_details: "Детали финансового отчета",
        total_income: "Общий доход",
        total_expenses: "Общие расходы",
        patient_dynamics: "Динамика пациентов",
        patient_report_details: "Детали отчета по пациентам",
        average_weekly: "Среднее за неделю",
        average_monthly: "Среднее за месяц",
        average_quarterly: "Среднее за квартал",
        average_weekly_patients: "Среднее количество пациентов за неделю:",
        average_monthly_patients: "Среднее количество пациентов за месяц:",
        average_quarterly_patients: "Среднее количество пациентов за квартал:",
        growth: "Рост",
        doctor_efficiency: "Эффективность врачей",
        top_performing_doctor: "Лучший врач",
        average_patients_per_doctor: "Среднее количество пациентов на врача",
        staff_performance_report: "Отчет о производительности персонала",
        period: "Период",
        month: "Месяц",
        quarter: "Квартал",
        year: "Год",
        week1: "1-я неделя",
        week2: "2-я неделя",
        week3: "3-я неделя",
        week4: "4-я неделя",
        january: "Январь",
        february: "Февраль",
        march: "Март",
        quarter1: "1-й квартал",
        quarter2: "2-й квартал",
        quarter3: "3-й квартал",
        quarter4: "4-й квартал",
        history: "История",
        withdraw_cash: "Снять деньги из кассы",
        download_report_function: "Функция загрузки отчета",
        withdrawal_success: "Снятие денег из кассы успешно выполнено",
        expense_history: "История расходов",
        category: "Категория",
        amount: "Сумма",
        description: "Описание",
        enter_amount: "Введите сумму",
        select_reason: "Выберите причину",
        enter_additional_description: "Введите дополнительное описание",
        confirm: "Подтвердить",

        // Withdrawal reasons
        salary: "Зарплата врачам",
        salary_increase: "Дополнительная зарплата врачам",
        utilities: "Коммунальные платежи",
        rent: "Арендная плата",
        supplies: "Покупка медицинского оборудования",
        medicine: "Покупка лекарств",
        repairs: "Ремонтные работы",
        marketing: "Маркетинговые расходы",
        taxes: "Налоги",
        other_expenses: "Другие расходы",
        other: "Другое",

        // Withdrawal descriptions
        salary_payment_description: "Выплата ежемесяч��ой зарплаты врачам",
        utilities_payment_description: "Оплата электричества и воды",
        supplies_payment_description: "Покупка нового медицинского оборудования",
        medicine_payment_description: "Покупка лекарств",
        salary_increase_description: "Дополнительная зарплата для Др. Азиза Каримова",
        rent_payment_description: "Ежемесячная арендная плата",
        all_branches: "Все филиалы",

        // Inpatient Rooms
        inpatient_rooms: "Палаты для стационарных больных",
        current_rooms: "Текущие палаты",
        room_history: "История палат",
        add_new_room: "Добавить новую палату",
        edit_room: "Редактировать палату",
        confirm_delete_room: "Вы действительно хотите удалить эту палату?",
        room_number: "Номер палаты",
        room_type: "Тип палаты",
        standard_room: "Стандартная палата",
        premium_room: "Премиум палата",
        intensive_care: "Интенсивная терапия",
        daily_rate: "Дневная ставка",
        available: "Доступна",
        occupied: "Занята",
        maintenance: "На ремонте",
        room: "Палата",
        type: "Тип",
        capacity: "Вместимость",
        description: "Описание",
        current_patients: "Текущие пациенты",
        no_patients_in_room: "В этой палате нет пациентов",
        assign_patient: "Назначить пациента",
        assign_patient_to_room: "Назначить пациента в палату",
        admission_date: "Дата поступления",
        expected_discharge_date: "Ожидаемая дата выписки",
        expected_discharge: "Ожидаемая выписка",
        remaining_days: "Оставшиеся дни",
        discharge: "Выписать",
        confirm_discharge_patient: "Вы действительно хотите выписать этого пациента?",
        add_payment: "Добавить оплату",
        add_payment_for: "Добавить оплату для",
        payment_method: "Способ оплаты",
        payment_date: "Дата оплаты",
        total_payment: "Общая оплата",
        room_occupancy_history: "История занятости палат",
        discharge_date: "Дата выписки",
        duration: "Продолжительность",
        days: "дней",
        no_room_history: "Нет истории палат",
        inpatient_rooms_statistics: "Статистика стационарных палат",
        total_rooms: "Всего палат",
        available_rooms: "Доступные палаты",
        occupied_rooms: "Занятые палаты",
        maintenance_rooms: "Палаты на ремонте",
        total_inpatients: "Всего стационарных пациентов",
        average_stay_duration: "Средняя продолжительность пребывания",
        occupancy_rate: "Уровень занятости",
        total_revenue: "Общий доход",
        average_daily_revenue: "Средний дневной доход",
        close: "Закрыть",
        search_rooms_patients: "Поиск палат и пациентов...",
        all_rooms: "Все палаты",
        select_nurse: "Выберите медсестру",
        morning_shift: "Утренняя смена",
        evening_shift: "Вечерняя смена",
        night_shift: "Ночная смена",
        critical: "В критическом состоянии",
        recovering: "Выздоравливает",
        active: "Активный",
    },
    en: {
        // Auth
        login: "Login",
        signup: "Sign Up",
        logout: "Logout",
        email: "Email",
        password: "Password",
        confirm_password: "Confirm Password",
        forgot_password: "Forgot Password?",
        remember_me: "Remember Me",
        request_access: "Request Access",
        loggingIn: "Logging in...",
        or: "or",
        noAccount: "Don't have an account?",
        signUp: "Sign Up",
        requestReceived: "Request Received",
        credentialsSentTo: "Login credentials will be sent to:",
        backToLogin: "Back to Login",
        loginInstructions: "Enter your credentials to log in",
        emailPasswordRequired: "Email and password are required",
        loginFailed: "Login failed",
        clinicName: "Clinic Name",
        enterClinicInfo: "Enter clinic information",
        submit: "Submit",
        back: "Back",

        // Roles
        director: "Director",
        admin: "Administrator",
        doctor: "Doctor",
        user: "User",

        // Dashboard
        dashboard: "Dashboard",
        staff: "Staff",
        cabinets: "Cabinets",
        patients: "Patients",
        appointments: "Appointments",
        reports: "Reports",
        settings: "Settings",
        notifications: "Notifications",
        profile: "Profile",
        loading: "Loading",
        allBranches: "All Branches",

        // Common
        search: "Search...",
        filters: "Filters",
        all: "All",
        active: "Active",
        inactive: "Inactive",
        add: "Add",
        save: "Save",
        cancel: "Cancel",
        edit: "Edit",
        delete: "Delete",
        actions: "Actions",
        name: "Name",
        status: "Status",
        branch: "Branch",
        branch1: "Branch 1",
        branch2: "Branch 2",
        branch3: "Branch 3",
        no_data_found: "No data found",
        statistics: "Statistics",
        close_stats: "Close Statistics",
        today: "Today",
        yesterday: "Yesterday",
        daysAgo: "days ago",
        markAllAsRead: "Mark All as Read",
        markAsRead: "Mark as Read",
        read: "Read",
        unread: "Unread",
        siteNews: "Site News",
        workNotifications: "Work Notifications",
        noNotifications: "No notifications",
        high: "High",
        medium: "Medium",
        low: "Low",
        priority: "Priority",
        settingsSaved: "Settings saved",
        guest: "Guest",

        // Staff
        add_new_staff: "Add New Staff",
        edit_staff: "Edit Staff",
        confirm_delete_staff: "Are you sure you want to delete this staff member?",
        position: "Position",
        department: "Department",
        phone: "Phone",
        monthly_salary: "Monthly Salary",
        vacation_status: "Vacation Status",
        on_vacation: "On Vacation",
        at_work: "At Work",
        vacation_period: "Vacation Period",
        vacation_period_example: "Example: 2023-05-20 - 2023-06-05",
        full_name: "Full Name",
        total_staff: "Total Staff",
        active_staff: "Active Staff",
        staff_on_vacation: "Staff on Vacation",
        total_salary: "Total Salary",
        role_distribution: "Role Distribution",
        currency: "sum",
        inactive_staff: "Inactive Staff",

        // Staff positions
        doctor: "Doctor",
        admin: "Admin",
        nurse: "Nurse",
        lab_technician: "Lab Technician",
        pharmacist: "Pharmacist",
        receptionist: "Receptionist",
        accountant: "Accountant",
        cleaner: "Cleaner",
        security: "Security",
        buyer: "Purchasing Specialist",
        manager: "Manager",

        // Cabinets
        add_new_cabinet: "Add New Cabinet",
        edit_cabinet: "Edit Cabinet",
        confirm_delete_cabinet: "Are you sure you want to delete this cabinet?",
        cabinet_number: "Cabinet Number",
        cabinet_name: "Cabinet Name",
        floor: "Floor",
        capacity: "Capacity",
        doctors_count: "doctors count",
        maintenance: "Under Maintenance",
        total_cabinets: "Total Cabinets",
        active_cabinets: "Active Cabinets",
        maintenance_cabinets: "Cabinets Under Maintenance",
        total_capacity: "Total Capacity",
        floor_distribution: "Floor Distribution",
        number: "Number",
        inactive_cabinets: "Inactive Cabinets",

        // Patients
        add_new_patient: "Add New Patient",
        edit_patient: "Edit Patient",
        confirm_delete_patient: "Are you sure you want to delete this patient?",
        age: "Age",
        gender: "Gender",
        male: "Male",
        female: "Female",
        address: "Address",
        diagnosis: "Diagnosis",
        doctor: "Doctor",
        last_visit: "Last Visit",
        export_to_pdf: "Export to PDF",
        export_to_excel: "Export to Excel",
        blood_group: "Blood Group",
        insurance: "Insurance",
        emergency_contact: "Emergency Contact",
        allergies: "Allergies",
        medical_history: "Medical History",
        patient_id: "Patient ID",
        registration_date: "Registration Date",
        patient_details: "Patient Details",
        patient_list: "Patient List",
        patient_statistics: "Patient Statistics",
        total_patients: "Total Patients",
        new_patients: "New Patients",
        returning_patients: "Returning Patients",
        patient_demographics: "Patient Demographics",
        age_distribution: "Age Distribution",
        gender_distribution: "Gender Distribution",
        visit_history: "Visit History",
        upcoming_appointments: "Upcoming Appointments",
        treatment_plan: "Treatment Plan",
        prescriptions: "Prescriptions",
        lab_results: "Lab Results",
        billing_info: "Billing Information",
        insurance_details: "Insurance Details",
        insurance_provider: "Insurance Provider",
        policy_number: "Policy Number",
        coverage_details: "Coverage Details",
        patient_notes: "Patient Notes",
        add_note: "Add Note",
        upload_documents: "Upload Documents",
        download_report: "Download Report",
        print_details: "Print Details",
        share_records: "Share Records",
        filter_by_doctor: "Filter by Doctor",
        filter_by_date: "Filter by Date",
        filter_by_status: "Filter by Status",
        sort_by_name: "Sort by Name",
        sort_by_date: "Sort by Date",
        sort_by_id: "Sort by ID",
        inactive_patients: "Inactive Patients",
        patients_count: "Patients Count",

        // Appointments
        add_new_appointment: "Add New Appointment",
        edit_appointment: "Edit Appointment",
        confirm_delete_appointment: "Are you sure you want to delete this appointment?",
        patient: "Patient",
        date: "Date",
        time: "Time",
        notes: "Notes",
        pending: "Pending",
        confirmed: "Confirmed",
        completed: "Completed",
        cancelled: "Cancelled",
        select_patient: "Select Patient",
        select_doctor: "Select Doctor",
        appointment_details: "Appointment Details",
        appointment_history: "Appointment History",
        upcoming_appointments: "Upcoming Appointments",
        past_appointments: "Past Appointments",
        appointment_status: "Appointment Status",
        reschedule: "Reschedule",
        cancel_appointment: "Cancel Appointment",
        appointment_type: "Appointment Type",
        duration: "Duration",
        reason: "Reason",
        symptoms: "Symptoms",
        appointment_notes: "Appointment Notes",
        follow_up: "Follow Up",
        appointment_reminder: "Appointment Reminder",
        send_reminder: "Send Reminder",
        reminder_sent: "Reminder Sent",
        appointment_fee: "Appointment Fee",
        payment_status: "Payment Status",
        paid: "Paid",
        unpaid: "Unpaid",
        partial: "Partial",
        payment_method: "Payment Method",
        cash: "Cash",
        card: "Card",
        insurance: "Insurance",
        appointment_location: "Appointment Location",
        online: "Online",
        in_person: "In Person",
        appointment_documents: "Appointment Documents",
        upload_documents: "Upload Documents",
        download_documents: "Download Documents",
        appointment_history_empty: "Appointment History Empty",
        no_upcoming_appointments: "No Upcoming Appointments",
        no_past_appointments: "No Past Appointments",
        appointment_created: "Appointment Created",
        appointment_updated: "Appointment Updated",
        appointment_deleted: "Appointment Deleted",
        appointment_confirmed: "Appointment Confirmed",
        appointment_completed: "Appointment Completed",
        appointment_cancelled: "Appointment Cancelled",
        appointment_rescheduled: "Appointment Rescheduled",

        // Profile
        personal_info: "Personal Information",
        change_password: "Change Password",
        language: "Language",
        save_changes: "Save Changes",
        current_password: "Current Password",
        new_password: "New Password",
        confirm_new_password: "Confirm New Password",
        profile_updated: "Profile Updated",
        password_changed: "Password Changed",
        passwords_do_not_match: "Passwords do not match",
        current_password_incorrect: "Current password is incorrect",
        profile_picture: "Profile Picture",
        upload_picture: "Upload Picture",
        remove_picture: "Remove Picture",
        account_settings: "Account Settings",
        notification_settings: "Notification Settings",
        email_notifications: "Email Notifications",
        sms_notifications: "SMS Notifications",
        app_notifications: "App Notifications",
        account_security: "Account Security",
        two_factor_authentication: "Two-Factor Authentication",
        enable: "Enable",
        disable: "Disable",
        account_activity: "Account Activity",
        last_login: "Last Login",
        last_password_change: "Last Password Change",
        devices: "Devices",
        logout_all_devices: "Logout All Devices",
        delete_account: "Delete Account",
        delete_account_warning: "This action is irreversible. Your account and all data will be deleted.",
        confirm_delete_account: "Confirm Delete Account",

        // Schedule
        schedule: "Schedule",
        availability: "Availability",
        working_hours: "Working Hours",
        days_off: "Days Off",
        vacation: "Vacation",
        sick_leave: "Sick Leave",
        personal_leave: "Personal Leave",
        schedule_settings: "Schedule Settings",
        auto_schedule: "Auto Schedule",
        manual_schedule: "Manual Schedule",
        schedule_conflicts: "Schedule Conflicts",
        resolve_conflicts: "Resolve Conflicts",
        schedule_templates: "Schedule Templates",
        create_template: "Create Template",
        apply_template: "Apply Template",
        delete_template: "Delete Template",
        schedule_export: "Export Schedule",
        import_schedule: "Import Schedule",
        schedule_notifications: "Schedule Notifications",
        schedule_changes: "Schedule Changes",
        schedule_reminders: "Schedule Reminders",
        schedule_conflicts_resolved: "Schedule Conflicts Resolved",
        schedule_updated: "Schedule Updated",
        schedule_template_created: "Schedule Template Created",
        schedule_template_applied: "Schedule Template Applied",
        schedule_template_deleted: "Schedule Template Deleted",
        schedule_exported: "Schedule Exported",
        schedule_imported: "Schedule Imported",
        schedule_notification_sent: "Schedule Notification Sent",
        schedule_reminder_sent: "Schedule Reminder Sent",

        // Settings
        generalSettings: "General Settings",
        branchSettings: "Branch Settings",
        financialSettings: "Financial Settings",
        userSettings: "User Settings",
        notificationSettings: "Notification Settings",
        securitySettings: "Security Settings",
        systemSettings: "System Settings",
        backupSettings: "Backup Settings",
        integrationSettings: "Integration Settings",
        apiSettings: "API Settings",
        branchName: "Branch Name",
        taxRate: "Tax Rate",
        workingHours: "Working Hours",
        workingDays: "Working Days",
        website: "Website",

        // Reports
        financialReports: "Financial Reports",
        patientReports: "Patient Reports",
        staffReports: "Staff Reports",
        inventoryReports: "Inventory Reports",
        appointmentReports: "Appointment Reports",
        customReports: "Custom Reports",
        reportPeriod: "Report Period",
        daily: "Daily",
        weekly: "Weekly",
        monthly: "Monthly",
        quarterly: "Quarterly",
        yearly: "Yearly",
        customPeriod: "Custom Period",
        startDate: "Start Date",
        endDate: "End Date",
        generateReport: "Generate Report",
        exportReport: "Export Report",
        printReport: "Print Report",
        saveReport: "Save Report",
        reportGenerated: "Report Generated",
        reportExported: "Report Exported",
        reportPrinted: "Report Printed",
        reportSaved: "Report Saved",
        noReportData: "No Report Data",
        reportSettings: "Report Settings",
        reportTemplate: "Report Template",
        reportFormat: "Report Format",
        includeCharts: "Include Charts",
        includeTables: "Include Tables",
        includeSummary: "Include Summary",
        revenueReport: "Revenue Report",
        expenseReport: "Expense Report",
        profitReport: "Profit Report",
        taxReport: "Tax Report",
        patientVisitReport: "Patient Visit Report",
        staffPerformanceReport: "Staff Performance Report",
        inventoryUsageReport: "Inventory Usage Report",
        appointmentCompletionReport: "Appointment Completion Report",

        // Director Reports
        financial: "Financial",
        income: "Income",
        expense: "Expense",
        net_profit: "Net Profit",
        profitability: "Profitability",
        financial_indicators: "Financial Indicators",
        financial_report_details: "Financial Report Details",
        total_income: "Total Income",
        total_expenses: "Total Expenses",
        patient_dynamics: "Patient Dynamics",
        patient_report_details: "Patient Report Details",
        average_weekly: "Average Weekly",
        average_monthly: "Average Monthly",
        average_quarterly: "Average Quarterly",
        average_weekly_patients: "Average Weekly Patients:",
        average_monthly_patients: "Average Monthly Patients:",
        average_quarterly_patients: "Average Quarterly Patients:",
        growth: "Growth",
        doctor_efficiency: "Doctor Efficiency",
        top_performing_doctor: "Top Performing Doctor",
        average_patients_per_doctor: "Average Patients per Doctor",
        staff_performance_report: "Staff Performance Report",
        period: "Period",
        month: "Month",
        quarter: "Quarter",
        year: "Year",
        week1: "Week 1",
        week2: "Week 2",
        week3: "Week 3",
        week4: "Week 4",
        january: "January",
        february: "February",
        march: "March",
        quarter1: "Quarter 1",
        quarter2: "Quarter 2",
        quarter3: "Quarter 3",
        quarter4: "Quarter 4",
        history: "History",
        withdraw_cash: "Withdraw Cash",
        download_report_function: "Download Report Function",
        withdrawal_success: "Cash withdrawal successful",
        expense_history: "Expense History",
        category: "Category",
        amount: "Amount",
        description: "Description",
        enter_amount: "Enter amount",
        select_reason: "Select reason",
        enter_additional_description: "Enter additional description",
        confirm: "Confirm",

        // Withdrawal reasons
        salary: "Salary for doctors",
        salary_increase: "Additional salary for doctors",
        utilities: "Utility payments",
        rent: "Rent payment",
        supplies: "Medical supplies purchase",
        medicine: "Medicine purchase",
        repairs: "Repair works",
        marketing: "Marketing expenses",
        taxes: "Taxes",
        other_expenses: "Other expenses",
        other: "Other",

        // Withdrawal descriptions
        salary_payment_description: "Monthly salary payment for doctors",
        utilities_payment_description: "Electricity and water payments",
        supplies_payment_description: "Purchase of new medical equipment",
        medicine_payment_description: "Purchase of medicines",
        salary_increase_description: "Additional salary for Dr. Aziz Karimov",
        rent_payment_description: "Monthly rent payment",
        all_branches: "All Branches",

        // Inpatient Rooms
        inpatient_rooms: "Inpatient Rooms",
        current_rooms: "Current Rooms",
        room_history: "Room History",
        add_new_room: "Add New Room",
        edit_room: "Edit Room",
        confirm_delete_room: "Are you sure you want to delete this room?",
        room_number: "Room Number",
        room_type: "Room Type",
        standard_room: "Standard Room",
        premium_room: "Premium Room",
        intensive_care: "Intensive Care",
        daily_rate: "Daily Rate",
        available: "Available",
        occupied: "Occupied",
        maintenance: "Maintenance",
        room: "Room",
        type: "Type",
        capacity: "Capacity",
        description: "Description",
        current_patients: "Current Patients",
        no_patients_in_room: "No patients in this room",
        assign_patient: "Assign Patient",
        assign_patient_to_room: "Assign Patient to Room",
        admission_date: "Admission Date",
        expected_discharge_date: "Expected Discharge Date",
        expected_discharge: "Expected Discharge",
        remaining_days: "Remaining Days",
        discharge: "Discharge",
        confirm_discharge_patient: "Are you sure you want to discharge this patient?",
        add_payment: "Add Payment",
        add_payment_for: "Add Payment for",
        payment_method: "Payment Method",
        payment_date: "Payment Date",
        total_payment: "Total Payment",
        room_occupancy_history: "Room Occupancy History",
        discharge_date: "Discharge Date",
        duration: "Duration",
        days: "days",
        no_room_history: "No room history",
        inpatient_rooms_statistics: "Inpatient Rooms Statistics",
        total_rooms: "Total Rooms",
        available_rooms: "Available Rooms",
        occupied_rooms: "Occupied Rooms",
        maintenance_rooms: "Maintenance Rooms",
        total_inpatients: "Total Inpatients",
        average_stay_duration: "Average Stay Duration",
        occupancy_rate: "Occupancy Rate",
        total_revenue: "Total Revenue",
        average_daily_revenue: "Average Daily Revenue",
        close: "Close",
        search_rooms_patients: "Search rooms and patients...",
        all_rooms: "All Rooms",
        select_nurse: "Select Nurse",
        morning_shift: "Morning Shift",
        evening_shift: "Evening Shift",
        night_shift: "Night Shift",
        critical: "Critical",
        recovering: "Recovering",
        active: "Active",
    },
    kz: {
        // Auth
        login: "Кіру",
        signup: "Тіркелу",
        logout: "Шығу",
        email: "Email",
        password: "Құпия сөз",
        confirm_password: "Құпия сөзді растаңыз",
        forgot_password: "Құпия сөзді ұмыттыңыз ба?",
        remember_me: "Мені есте сақтау",
        request_access: "Кіру рұқсатын сұрау",
        loggingIn: "Кіру...",
        or: "немесе",
        noAccount: "Тіркелгіңіз жоқ па?",
        signUp: "Тіркелу",
        requestReceived: "Сұрауыңыз қабылданды",
        credentialsSentTo: "Кіру деректері мына поштаға жіберіледі:",
        backToLogin: "Кіруге оралу",
        loginInstructions: "Жүйеге кіру үшін деректеріңізді енгізіңіз",
        emailPasswordRequired: "Email және құпия сөз қажет",
        loginFailed: "Кіру сәтсіз аяқталды",
        clinicName: "Клиника атауы",
        enterClinicInfo: "Клиника туралы ақпаратты енгізіңіз",
        submit: "Жіберу",
        back: "Артқа",

        // Roles
        director: "Директор",
        admin: "Әкімші",
        doctor: "Дәрігер",
        user: "Пайдаланушы",

        // Dashboard
        dashboard: "Басқару тақтасы",
        staff: "Қызметкерлер",
        cabinets: "Кабинеттер",
        patients: "Науқастар",
        appointments: "Қабылдаулар",
        reports: "Есептер",
        settings: "Параметрлер",
        notifications: "Хабарландырулар",
        profile: "Профиль",
        loading: "Жүктелуде",
        allBranches: "Барлық филиалдар",

        // Common
        search: "Іздеу...",
        filters: "Сүзгілер",
        all: "Барлығы",
        active: "Белсенді",
        inactive: "Белсенді емес",
        add: "Қосу",
        save: "Сақтау",
        cancel: "Болдырмау",
        edit: "Өңдеу",
        delete: "Жою",
        actions: "Әрекеттер",
        name: "Аты",
        status: "Күй",
        branch: "Филиал",
        branch1: "1-Филиал",
        branch2: "2-Филиал",
        branch3: "3-Филиал",
        no_data_found: "Деректер табылмады",
        statistics: "Статистика",
        close_stats: "Статистиканы жабу",
        today: "Бүгін",
        yesterday: "Кеше",
        daysAgo: "күн бұрын",
        markAllAsRead: "Барлығын оқылған деп белгілеу",
        markAsRead: "Оқылған деп белгілеу",
        read: "Оқылған",
        unread: "Оқылмаған",
        siteNews: "Сайт жаңалықтары",
        workNotifications: "Жұмыс хабарландырулары",
        noNotifications: "Хабарландырулар жоқ",
        high: "Жоғары",
        medium: "Орташа",
        low: "Төмен",
        priority: "Басымдық",
        settingsSaved: "Параметрлер сақталды",
        guest: "Қонақ",

        // Staff
        add_new_staff: "Жаңа қызметкер қосу",
        edit_staff: "Қызметкерді өңдеу",
        confirm_delete_staff: "Бұл қызметкерді шынымен жойғыңыз келе ме?",
        position: "Лауазым",
        department: "Бөлім",
        phone: "Телефон",
        monthly_salary: "Айлық жалақы",
        vacation_status: "Демалыс күйі",
        on_vacation: "Демалыста",
        at_work: "Жұмыста",
        vacation_period: "Демалыс кезеңі",
        vacation_period_example: "Мысал: 2023-05-20 - 2023-06-05",
        full_name: "Толық аты",
        total_staff: "Барлық қызметкерлер",
        active_staff: "Белсенді қызметкерлер",
        staff_on_vacation: "Демалыстағы қызметкерлер",
        total_salary: "Жалпы жалақы",
        role_distribution: "Лауазымдар бойынша бөлу",
        currency: "сом",
        inactive_staff: "Белсенді емес қызметкерлер",

        // Staff positions
        doctor: "Дәрігер",
        admin: "Әкімші",
        nurse: "Мейірбике",
        lab_technician: "Зертханашы",
        pharmacist: "Фармацевт",
        receptionist: "Қабылдау бөлімінің қызметкері",
        accountant: "Бухгалтер",
        cleaner: "Тазалаушы",
        security: "Күзетші",
        buyer: "Сатып алу маманы",
        manager: "Менеджер",

        // Cabinets
        add_new_cabinet: "Жаңа кабинет қосу",
        edit_cabinet: "Кабинетті өңдеу",
        confirm_delete_cabinet: "Бұл кабинетті шынымен жойғыңыз келе ме?",
        cabinet_number: "Кабинет нөмірі",
        cabinet_name: "Кабинет атауы",
        floor: "Қабат",
        capacity: "Сыйымдылық",
        doctors_count: "дәрігерлер саны",
        maintenance: "Жөндеуде",
        total_cabinets: "Барлық кабинеттер",
        active_cabinets: "Белсенді кабинеттер",
        maintenance_cabinets: "Жөндеудегі кабинеттер",
        total_capacity: "Жалпы сыйымдылық",
        floor_distribution: "Қабаттар бойынша бөлу",
        number: "Нөмір",
        inactive_cabinets: "Белсенді емес кабинеттер",

        // Patients
        add_new_patient: "Жаңа науқас қосу",
        edit_patient: "Науқасты өңдеу",
        confirm_delete_patient: "Бұл науқасты шынымен жойғыңыз келе ме?",
        age: "Жас",
        gender: "Жыныс",
        male: "Ер",
        female: "Әйел",
        address: "Мекенжай",
        diagnosis: "Диагноз",
        doctor: "Дәрігер",
        last_visit: "Соңғы келу",
        export_to_pdf: "PDF форматында жүктеу",
        export_to_excel: "Excel форматында жүктеу",
        blood_group: "Қан тобы",
        insurance: "Сақтандыру",
        emergency_contact: "Төтенше байланыс",
        allergies: "Аллергиялар",
        medical_history: "Медициналық тарих",
        patient_id: "Науқас ID",
        registration_date: "Тіркелу күні",
        patient_details: "Науқас мәліметтері",
        patient_list: "Науқастар тізімі",
        patient_statistics: "Науқастар статистикасы",
        total_patients: "Барлық науқастар",
        new_patients: "Жаңа науқастар",
        returning_patients: "Қайта келген науқастар",
        patient_demographics: "Науқастар демографиясы",
        age_distribution: "Жас бойынша бөлу",
        gender_distribution: "Жыныс бойынша бөлу",
        visit_history: "Келу тарихы",
        upcoming_appointments: "Алдағы қабылдаулар",
        treatment_plan: "Емдеу жоспары",
        prescriptions: "Рецептер",
        lab_results: "Зертхана нәтижелері",
        billing_info: "Төлем ақпараты",
        insurance_details: "Сақтандыру мәліметтері",
        insurance_provider: "Сақтандыру провайдері",
        policy_number: "Полис нөмірі",
        coverage_details: "Қамту мәліметтері",
        patient_notes: "Науқас жазбалары",
        add_note: "Жазба қосу",
        upload_documents: "Құжаттарды жүктеу",
        download_report: "Есепті жүктеу",
        print_details: "Мәліметтерді басып шығару",
        share_records: "Жазбаларды бөлісу",
        filter_by_doctor: "Дәрігер бойынша сүзу",
        filter_by_date: "Күн бойынша сүзу",
        filter_by_status: "Күй бойынша сүзу",
        sort_by_name: "Аты бойынша сұрыптау",
        sort_by_date: "Күні бойынша сұрыптау",
        sort_by_id: "ID бойынша сұрыптау",
        inactive_patients: "Белсенді емес науқастар",
        patients_count: "Науқастар саны",

        // Appointments
        add_new_appointment: "Жаңа қабылдау қосу",
        edit_appointment: "Қабылдауды өңдеу",
        confirm_delete_appointment: "Бұл қабылдауды шынымен жойғыңыз келе ме?",
        patient: "Науқас",
        date: "Күн",
        time: "Уақыт",
        notes: "Ескертпелер",
        pending: "Күтілуде",
        confirmed: "Расталған",
        completed: "Аяқталған",
        cancelled: "Болдырылмаған",
        select_patient: "Науқасты таңдаңыз",
        select_doctor: "Дәрігерді таңдаңыз",
        appointment_details: "Қабылдау мәліметтері",
        appointment_history: "Қабылдау тарихы",
        upcoming_appointments: "Алдағы қабылдаулар",
        past_appointments: "Өткен қабылдаулар",
        appointment_status: "Қабылдау күйі",
        reschedule: "Қайта жоспарлау",
        cancel_appointment: "Қабылдауды болдырмау",
        appointment_type: "Қабылдау түрі",
        duration: "Ұзақтығы",
        reason: "Себеп",
        symptoms: "Белгілер",
        appointment_notes: "Қабылдау жазбалары",
        follow_up: "Келесі қабылдау",
        appointment_reminder: "Қабылдау еске салғышы",
        send_reminder: "Еске салғыш жіберу",
        reminder_sent: "Еске салғыш жіберілді",
        appointment_fee: "Қабылдау төлемі",
        payment_status: "Төлем күйі",
        paid: "Төленген",
        unpaid: "Төленбеген",
        partial: "Жартылай төленген",
        payment_method: "Төлем әдісі",
        cash: "Қолма-қол ақша",
        card: "Карта",
        insurance: "Сақтандыру",
        appointment_location: "Қабылдау орны",
        online: "Онлайн",
        in_person: "Жеке",
        appointment_documents: "Қабылдау құжаттары",
        upload_documents: "Құжаттарды жүктеу",
        download_documents: "Құжаттарды жүктеу",
        appointment_history_empty: "Қабылдау тарихы бос",
        no_upcoming_appointments: "Алдағы қабылдаулар жоқ",
        no_past_appointments: "Өткен қабылдаулар жоқ",
        appointment_created: "Қабылдау жасалды",
        appointment_updated: "Қабылдау жаңартылды",
        appointment_deleted: "Қабылдау жойылды",
        appointment_confirmed: "Қабылдау расталды",
        appointment_completed: "Қабылдау аяқталды",
        appointment_cancelled: "Қабылдау болдырылмады",
        appointment_rescheduled: "Қабылдау қайта жоспарланды",

        // Profile
        personal_info: "Жеке ақпарат",
        change_password: "Құпия сөзді өзгерту",
        language: "Тіл",
        save_changes: "Өзгерістерді сақтау",
        current_password: "Ағымдағы құпия сөз",
        new_password: "Жаңа құпия сөз",
        confirm_new_password: "Жаңа құпия сөзді растаңыз",
        profile_updated: "Профиль жаңартылды",
        password_changed: "Құпия сөз өзгертілді",
        passwords_do_not_match: "Құпия сөздер сәйкес келмейді",
        current_password_incorrect: "Ағымдағы құпия сөз дұрыс емес",
        profile_picture: "Профиль суреті",
        upload_picture: "Сурет жүктеу",
        remove_picture: "Суретті жою",
        account_settings: "Тіркелгі параметрлері",
        notification_settings: "Хабарландыру параметрлері",
        email_notifications: "Email хабарландырулар",
        sms_notifications: "SMS хабарландырулар",
        app_notifications: "Қолданба хабарландырулары",
        account_security: "Тіркелгі қауіпсіздігі",
        two_factor_authentication: "Екі факторлы аутентификация",
        enable: "Қосу",
        disable: "Өшіру",
        account_activity: "Тіркелгі белсенділігі",
        last_login: "Соңғы кіру",
        last_password_change: "Соңғы құпия сөз өзгерісі",
        devices: "Құрылғылар",
        logout_all_devices: "Барлық құрылғылардан шығу",
        delete_account: "Тіркелгіні жою",
        delete_account_warning: "Бұл әрекет қайтымсыз. Тіркелгіңіз және барлық деректеріңіз жойылады.",
        confirm_delete_account: "Тіркелгіні жоюды растаңыз",

        // Schedule
        schedule: "Кесте",
        availability: "Қолжетімділік",
        working_hours: "Жұмыс сағаттары",
        days_off: "Демалыс күндері",
        vacation: "Демалыс",
        sick_leave: "Науқастану демалысы",
        personal_leave: "Жеке демалыс",
        schedule_settings: "Кесте параметрлері",
        auto_schedule: "Автоматты кесте",
        manual_schedule: "Қолмен кесте",
        schedule_conflicts: "Кесте қақтығыстары",
        resolve_conflicts: "Қақтығыстарды шешу",
        schedule_templates: "Кесте үлгілері",
        create_template: "Үлгі жасау",
        apply_template: "Үлгіні қолдану",
        delete_template: "Үлгіні жою",
        schedule_export: "Кестені экспорттау",
        import_schedule: "Кестені импорттау",
        schedule_notifications: "Кесте хабарландырулары",
        schedule_changes: "Кесте өзгерістері",
        schedule_reminders: "Кесте еске салғыштары",
        schedule_conflicts_resolved: "Кесте қақтығыстары шешілді",
        schedule_updated: "Кесте жаңартылды",
        schedule_template_created: "Кесте үлгісі жасалды",
        schedule_template_applied: "Кесте үлгісі қолданылды",
        schedule_template_deleted: "Кесте үлгісі жойылды",
        schedule_exported: "Кесте экспортталды",
        schedule_imported: "Кесте импортталды",
        schedule_notification_sent: "Кесте хабарландыруы жіберілді",
        schedule_reminder_sent: "Кесте еске салғышы жіберілді",

        // Settings
        generalSettings: "Жалпы параметрлер",
        branchSettings: "Филиал параметрлері",
        financialSettings: "Қаржылық параметрлер",
        userSettings: "Пайдаланушы параметрлері",
        notificationSettings: "Хабарландыру параметрлері",
        securitySettings: "Қауіпсіздік параметрлері",
        systemSettings: "Жүйе параметрлері",
        backupSettings: "Резервтік көшірме параметрлері",
        integrationSettings: "Интеграция параметрлері",
        apiSettings: "API параметрлері",
        branchName: "Филиал атауы",
        taxRate: "Салық мөлшерлемесі",
        workingHours: "Жұмыс сағаттары",
        workingDays: "Жұмыс күндері",
        website: "Веб-сайт",

        // Reports
        financialReports: "Қаржылық есептер",
        patientReports: "Науқас есептері",
        staffReports: "Қызметкер есептері",
        inventoryReports: "Инвентарь есептері",
        appointmentReports: "Қабылдау есептері",
        customReports: "Арнайы есептер",
        reportPeriod: "Есеп кезеңі",
        daily: "Күнделікті",
        weekly: "Апта сайын",
        monthly: "Ай сайын",
        quarterly: "Тоқсан сайын",
        yearly: "Жыл сайын",
        customPeriod: "Арнайы кезең",
        startDate: "Басталу күні",
        endDate: "Аяқталу күні",
        generateReport: "Есеп жасау",
        exportReport: "Есепті экспорттау",
        printReport: "Есепті басып шығару",
        saveReport: "Есепті сақтау",
        reportGenerated: "Есеп жасалды",
        reportExported: "Есеп экспортталды",
        reportPrinted: "Есеп басып шығарылды",
        reportSaved: "Есеп сақталды",
        noReportData: "Есеп деректері жоқ",
        reportSettings: "Есеп параметрлері",
        reportTemplate: "Есеп үлгісі",
        reportFormat: "Есеп форматы",
        includeCharts: "Диаграммаларды қосу",
        includeTables: "Кестелерді қосу",
        includeSummary: "Қорытындыны қосу",
        revenueReport: "Кіріс есебі",
        expenseReport: "Шығыс есебі",
        profitReport: "Пайда есебі",
        taxReport: "Салық есебі",
        patientVisitReport: "Науқас келу есебі",
        staffPerformanceReport: "Қызметкер өнімділігі есебі",
        inventoryUsageReport: "Инвентарь пайдалану есебі",
        appointmentCompletionReport: "Қабылдау аяқталу есебі",

        // Director Reports
        financial: "Қаржылық",
        income: "Кіріс",
        expense: "Шығыс",
        net_profit: "Таза пайда",
        profitability: "Рентабельділік",
        financial_indicators: "Қаржылық көрсеткіштер",
        financial_report_details: "Қаржылық есеп мәліметтері",
        total_income: "Жалпы кіріс",
        total_expenses: "Жалпы шығыс",
        patient_dynamics: "Науқастар динамикасы",
        patient_report_details: "Науқастар есебінің мәліметтері",
        average_weekly: "Апта сайынғы орташа",
        average_monthly: "Ай сайынғы орташа",
        average_quarterly: "Тоқсан сайынғы орташа",
        average_weekly_patients: "Апта сайынғы орташа науқастар:",
        average_monthly_patients: "Ай сайынғы орташа науқастар:",
        average_quarterly_patients: "Тоқсан сайынғы орташа науқастар:",
        growth: "Өсу",
        doctor_efficiency: "Дәрігерлер тиімділігі",
        top_performing_doctor: "Ең тиімді дәрігер",
        average_patients_per_doctor: "Дәрігер басына орташа науқас",
        staff_performance_report: "Қызметкерлер өнімділігі есебі",
        period: "Кезең",
        month: "Ай",
        quarter: "Тоқсан",
        year: "Жыл",
        week1: "1-апта",
        week2: "2-апта",
        week3: "3-апта",
        week4: "4-апта",
        january: "Қаңтар",
        february: "Ақпан",
        march: "Наурыз",
        quarter1: "1-тоқсан",
        quarter2: "2-тоқсан",
        quarter3: "3-тоқсан",
        quarter4: "4-тоқсан",
        history: "Тарих",
        withdraw_cash: "Кассадан ақша алу",
        download_report_function: "Есепті жүктеу функциясы",
        withdrawal_success: "Кассадан ақша алу сәтті аяқталды",
        expense_history: "Шығыстар тарихы",
        category: "Категория",
        amount: "Сома",
        description: "Сипаттама",
        enter_amount: "Соманы енгізіңіз",
        select_reason: "Себепті таңдаңыз",
        enter_additional_description: "Қосымша сипаттама енгізіңіз",
        confirm: "Растау",

        // Withdrawal reasons
        salary: "Дәрігерлерге жалақы",
        salary_increase: "Дәрігерлерге қосымша жалақы",
        utilities: "Коммуналдық төлемдер",
        rent: "Жалдау төлемі",
        supplies: "Медициналық жабдықтар сатып алу",
        medicine: "Дәрі-дәрмектер сатып алу",
        repairs: "Жөндеу жұмыстары",
        marketing: "Маркетинг шығындары",
        taxes: "Салықтар",
        other_expenses: "Басқа шығындар",
        other: "Басқа",

        // Withdrawal descriptions
        salary_payment_description: "Дәрігерлерге айлық жалақы төлемі",
        utilities_payment_description: "Электр және су төлемдері",
        supplies_payment_description: "Жаңа медициналық жабдықтар сатып алу",
        medicine_payment_description: "Дәрі-дәрмектер сатып алу",
        salary_increase_description: "Др. Азиз Каримовқа қосымша жалақы",
        rent_payment_description: "Айлық жалдау төлемі",
        all_branches: "Барлық филиалдар",

        // Inpatient Rooms
        inpatient_rooms: "Стационар бөлмелері",
        current_rooms: "Ағымдағы бөлмелер",
        room_history: "Бөлмелер тарихы",
        add_new_room: "Жаңа бөлме қосу",
        edit_room: "Бөлмені өңдеу",
        confirm_delete_room: "Бұл бөлмені шынымен жойғыңыз келе ме?",
        room_number: "Бөлме нөмірі",
        room_type: "Бөлме түрі",
        standard_room: "Стандартты бөлме",
        premium_room: "Премиум бөлме",
        intensive_care: "Қарқынды терапия",
        daily_rate: "Күндік баға",
        available: "Қолжетімді",
        occupied: "Бос емес",
        maintenance: "Жөндеуде",
        room: "Бөлме",
        type: "Түрі",
        capacity: "Сыйымдылық",
        description: "Сипаттама",
        current_patients: "Ағымдағы науқастар",
        no_patients_in_room: "Бұл бөлмеде науқастар жоқ",
        assign_patient: "Науқасты тағайындау",
        assign_patient_to_room: "Науқасты бөлмеге тағайындау",
        admission_date: "Қабылдау күні",
        expected_discharge_date: "Күтілетін шығару күні",
        expected_discharge: "Күтілетін шығару",
        remaining_days: "Қалған күндер",
        discharge: "Шығару",
        confirm_discharge_patient: "Бұл науқасты шынымен шығарғыңыз келе ме?",
        add_payment: "Төлем қосу",
        add_payment_for: "Үшін төлем қосу",
        payment_method: "Төлем әдісі",
        payment_date: "Төлем күні",
        total_payment: "Жалпы төлем",
        room_occupancy_history: "Бөлме жүктеме тарихы",
        discharge_date: "Шығару күні",
        duration: "Ұзақтық",
        days: "күн",
        no_room_history: "Бөлме тарихы жоқ",
        inpatient_rooms_statistics: "Стационар бөлмелері статистикасы",
        total_rooms: "Барлық бөлмелер",
        available_rooms: "Қолжетімді бөлмелер",
        occupied_rooms: "Бос емес бөлмелер",
        maintenance_rooms: "Жөндеудегі бөлмелер",
        total_inpatients: "Барлық стационар науқастар",
        average_stay_duration: "Орташа болу ұзақтығы",
        occupancy_rate: "Жүктеме деңгейі",
        total_revenue: "Жалпы кіріс",
        average_daily_revenue: "Орташа күндік кіріс",
        close: "Жабу",
        search_rooms_patients: "Бөлмелер мен науқастарды іздеу...",
        all_rooms: "Барлық бөлмелер",
        select_nurse: "Мейірбикені таңдаңыз",
        morning_shift: "Таңғы ауысым",
        evening_shift: "Кешкі ауысым",
        night_shift: "Түнгі ауысым",
        critical: "Ауыр жағдайда",
        recovering: "Сауығу үстінде",
        active: "Белсенді",
    },
    zh: {
        // Auth
        login: "登录",
        signup: "注册",
        logout: "退出",
        email: "电子邮件",
        password: "密码",
        confirm_password: "确认密码",
        forgot_password: "忘记密码？",
        remember_me: "记住我",
        request_access: "请求访问",
        loggingIn: "登录中...",
        or: "或",
        noAccount: "没有账号？",
        signUp: "注册",
        requestReceived: "请求已收到",
        credentialsSentTo: "登录凭证将发送至：",
        backToLogin: "返回登录",
        loginInstructions: "输入您的凭证以登录",
        emailPasswordRequired: "需要电子邮件和密码",
        loginFailed: "登录失败",
        clinicName: "诊所名称",
        enterClinicInfo: "输入诊所信息",
        submit: "提交",
        back: "返回",

        // Roles
        director: "主任",
        admin: "管理员",
        doctor: "医生",
        user: "用户",

        // Dashboard
        dashboard: "仪表板",
        staff: "员工",
        cabinets: "诊室",
        patients: "患者",
        appointments: "预约",
        reports: "报告",
        settings: "设置",
        notifications: "通知",
        profile: "个人资料",
        loading: "加载中",
        allBranches: "所有分支",

        // Common
        search: "搜索...",
        filters: "筛选",
        all: "全部",
        active: "活跃",
        inactive: "不活跃",
        add: "添加",
        save: "保存",
        cancel: "取消",
        edit: "编辑",
        delete: "删除",
        actions: "操作",
        name: "姓名",
        status: "状态",
        branch: "分支",
        branch1: "分支1",
        branch2: "分支2",
        branch3: "分支3",
        no_data_found: "未找到数据",
        statistics: "统计",
        close_stats: "关闭统计",
        today: "今天",
        yesterday: "昨天",
        daysAgo: "天前",
        markAllAsRead: "标记所有为已读",
        markAsRead: "标记为已读",
        read: "已读",
        unread: "未读",
        siteNews: "网站新闻",
        workNotifications: "工作通知",
        noNotifications: "没有通知",
        high: "高",
        medium: "中",
        low: "低",
        priority: "优先级",
        settingsSaved: "设置已保存",
        guest: "访客",

        // Staff
        add_new_staff: "添加新员工",
        edit_staff: "编辑员工",
        confirm_delete_staff: "您确定要删除此员工吗？",
        position: "职位",
        department: "部门",
        phone: "电话",
        monthly_salary: "月薪",
        vacation_status: "休假状态",
        on_vacation: "休假中",
        at_work: "工作中",
        vacation_period: "休假期间",
        vacation_period_example: "例如：2023-05-20 - 2023-06-05",
        full_name: "全名",
        total_staff: "员工总数",
        active_staff: "活跃员工",
        staff_on_vacation: "休假员工",
        total_salary: "总薪资",
        role_distribution: "职位分布",
        currency: "苏姆",
        inactive_staff: "不活跃员工",

        // Staff positions
        doctor: "医生",
        admin: "管理员",
        nurse: "护士",
        lab_technician: "实验室技术员",
        pharmacist: "药剂师",
        receptionist: "接待员",
        accountant: "会计",
        cleaner: "清洁工",
        security: "保安",
        buyer: "采购专员",
        manager: "经理",

        // Cabinets
        add_new_cabinet: "添加新诊室",
        edit_cabinet: "编辑诊室",
        confirm_delete_cabinet: "您确定要删除此诊室吗？",
        cabinet_number: "诊室号",
        cabinet_name: "诊室名称",
        floor: "楼层",
        capacity: "容量",
        doctors_count: "医生数量",
        maintenance: "维护中",
        total_cabinets: "诊室总数",
        active_cabinets: "活跃诊室",
        maintenance_cabinets: "维护中的诊室",
        total_capacity: "总容量",
        floor_distribution: "楼层分布",
        number: "编号",
        inactive_cabinets: "不活跃诊室",

        // Patients
        add_new_patient: "添加新患者",
        edit_patient: "编辑患者",
        confirm_delete_patient: "您确定要删除此患者吗？",
        age: "年龄",
        gender: "性别",
        male: "男",
        female: "女",
        address: "地址",
        diagnosis: "诊断",
        doctor: "医生",
        last_visit: "上次就诊",
        export_to_pdf: "导出为PDF",
        export_to_excel: "导出为Excel",
        blood_group: "血型",
        insurance: "保险",
        emergency_contact: "紧急联系人",
        allergies: "过敏症",
        medical_history: "病史",
        patient_id: "患者ID",
        registration_date: "注册日期",
        patient_details: "患者详情",
        patient_list: "患者列表",
        patient_statistics: "患者统计",
        total_patients: "患者总数",
        new_patients: "新患者",
        returning_patients: "回访患者",
        patient_demographics: "患者人口统计",
        age_distribution: "年龄分布",
        gender_distribution: "性别分布",
        visit_history: "就诊历史",
        upcoming_appointments: "即将到来的预约",
        treatment_plan: "治疗计划",
        prescriptions: "处方",
        lab_results: "实验室结果",
        billing_info: "账单信息",
        insurance_details: "保险详情",
        insurance_provider: "保险提供商",
        policy_number: "保单号码",
        coverage_details: "保障详情",
        patient_notes: "患者笔记",
        add_note: "添加笔记",
        upload_documents: "上传文档",
        download_report: "下载报告",
        print_details: "打印详情",
        share_records: "分享记录",
        filter_by_doctor: "按医生筛选",
        filter_by_date: "按日期筛选",
        filter_by_status: "按状态筛选",
        sort_by_name: "按姓名排序",
        sort_by_date: "按日期排序",
        sort_by_id: "按ID排序",
        inactive_patients: "不活跃患者",
        patients_count: "患者数量",

        // Appointments
        add_new_appointment: "添加新预约",
        edit_appointment: "编辑预约",
        confirm_delete_appointment: "您确定要删除此预约吗？",
        patient: "患者",
        date: "日期",
        time: "时间",
        notes: "备注",
        pending: "待处理",
        confirmed: "已确认",
        completed: "已完成",
        cancelled: "已取消",
        select_patient: "选择患者",
        select_doctor: "选择医生",
        appointment_details: "预约详情",
        appointment_history: "预约历史",
        upcoming_appointments: "即将到来的预约",
        past_appointments: "过去的预约",
        appointment_status: "预约状态",
        reschedule: "重新安排",
        cancel_appointment: "取消预约",
        appointment_type: "预约类型",
        duration: "持续时间",
        reason: "原因",
        symptoms: "症状",
        appointment_notes: "预约备注",
        follow_up: "后续预约",
        appointment_reminder: "预约提醒",
        send_reminder: "发送提醒",
        reminder_sent: "提醒已发送",
        appointment_fee: "预约费用",
        payment_status: "支付状态",
        paid: "已支付",
        unpaid: "未支付",
        partial: "部分支付",
        payment_method: "支付方式",
        cash: "现金",
        card: "卡",
        insurance: "保险",
        appointment_location: "预约地点",
        online: "在线",
        in_person: "亲自",
        appointment_documents: "预约文档",
        upload_documents: "上传文档",
        download_documents: "下载文档",
        appointment_history_empty: "预约历史为空",
        no_upcoming_appointments: "没有即将到来的预约",
        no_past_appointments: "没有过去的预约",
        appointment_created: "预约已创建",
        appointment_updated: "预约已更新",
        appointment_deleted: "预约已删除",
        appointment_confirmed: "预约已确认",
        appointment_completed: "预约已完成",
        appointment_cancelled: "预约已取消",
        appointment_rescheduled: "预约已重新安排",

        // Profile
        personal_info: "个人信息",
        change_password: "更改密码",
        language: "语言",
        save_changes: "保存更改",
        current_password: "当前密码",
        new_password: "新密码",
        confirm_new_password: "确认新密码",
        profile_updated: "个人资料已更新",
        password_changed: "密码已更改",
        passwords_do_not_match: "密码不匹配",
        current_password_incorrect: "当前密码不正确",
        profile_picture: "个人头像",
        upload_picture: "上传图片",
        remove_picture: "删除图片",
        account_settings: "账户设置",
        notification_settings: "通知设置",
        email_notifications: "电子邮件通知",
        sms_notifications: "短信通知",
        app_notifications: "应用通知",
        account_security: "账户安全",
        two_factor_authentication: "双因素认证",
        enable: "启用",
        disable: "禁用",
        account_activity: "账户活动",
        last_login: "上次登录",
        last_password_change: "上次密码更改",
        devices: "设备",
        logout_all_devices: "登出所有设备",
        delete_account: "删除账户",
        delete_account_warning: "此操作不可逆。您的账户和所有数据将被删除。",
        confirm_delete_account: "确认删除账户",

        // Schedule
        schedule: "日程",
        availability: "可用性",
        working_hours: "工作时间",
        days_off: "休息日",
        vacation: "假期",
        sick_leave: "病假",
        personal_leave: "个人假期",
        schedule_settings: "日程设置",
        auto_schedule: "自动日程",
        manual_schedule: "手动日程",
        schedule_conflicts: "日程冲突",
        resolve_conflicts: "解决冲突",
        schedule_templates: "日程模板",
        create_template: "创建模板",
        apply_template: "应用模板",
        delete_template: "删除模板",
        schedule_export: "导出日程",
        import_schedule: "导入日程",
        schedule_notifications: "日程通知",
        schedule_changes: "日程变更",
        schedule_reminders: "日程提醒",
        schedule_conflicts_resolved: "日程冲突已解决",
        schedule_updated: "日程已更新",
        schedule_template_created: "日程模板已创建",
        schedule_template_applied: "日程模板已应用",
        schedule_template_deleted: "日程模板已删除",
        schedule_exported: "日程已导出",
        schedule_imported: "日程已导入",
        schedule_notification_sent: "日程通知已发送",
        schedule_reminder_sent: "日程提醒已发送",

        // Settings
        generalSettings: "常规设置",
        branchSettings: "分支设置",
        financialSettings: "财务设置",
        userSettings: "用户设置",
        notificationSettings: "通知设置",
        securitySettings: "安全设置",
        systemSettings: "系统设置",
        backupSettings: "备份设置",
        integrationSettings: "集成设置",
        apiSettings: "API设置",
        branchName: "分支名称",
        taxRate: "税率",
        workingHours: "工作时间",
        workingDays: "工作日",
        website: "网站",

        // Reports
        financialReports: "财务报告",
        patientReports: "患者报告",
        staffReports: "员工报告",
        inventoryReports: "库存报告",
        appointmentReports: "预约报告",
        customReports: "自定义报告",
        reportPeriod: "报告周期",
        daily: "每日",
        weekly: "每周",
        monthly: "每月",
        quarterly: "每季度",
        yearly: "每年",
        customPeriod: "自定义周期",
        startDate: "开始日期",
        endDate: "结束日期",
        generateReport: "生成报告",
        exportReport: "导出报告",
        printReport: "打印报告",
        saveReport: "保存报告",
        reportGenerated: "报告已生成",
        reportExported: "报告已导出",
        reportPrinted: "报告已打印",
        reportSaved: "报告已保存",
        noReportData: "没有报告数据",
        reportSettings: "报告设置",
        reportTemplate: "报告模板",
        reportFormat: "报告格式",
        includeCharts: "包含图表",
        includeTables: "包含表格",
        includeSummary: "包含摘要",
        revenueReport: "收入报告",
        expenseReport: "支出报告",
        profitReport: "利润报告",
        taxReport: "税务报告",
        patientVisitReport: "患者就诊报告",
        staffPerformanceReport: "员工绩效报告",
        inventoryUsageReport: "库存使用报告",
        appointmentCompletionReport: "预约完成报告",

        // Director Reports
        financial: "财务",
        income: "收入",
        expense: "支出",
        net_profit: "净利润",
        profitability: "盈利能力",
        financial_indicators: "财务指标",
        financial_report_details: "财务报告详情",
        total_income: "总收入",
        total_expenses: "总支出",
        patient_dynamics: "患者动态",
        patient_report_details: "患者报告详情",
        average_weekly: "每周平均",
        average_monthly: "每月平均",
        average_quarterly: "每季度平均",
        average_weekly_patients: "每周平均患者数:",
        average_monthly_patients: "每月平均患者数:",
        average_quarterly_patients: "每季度平均患者数:",
        growth: "增长",
        doctor_efficiency: "医生效率",
        top_performing_doctor: "表现最佳医生",
        average_patients_per_doctor: "每位医生平均患者数",
        staff_performance_report: "员工绩效报告",
        period: "周期",
        month: "月",
        quarter: "季度",
        year: "年",
        week1: "第1周",
        week2: "第2周",
        week3: "第3周",
        week4: "第4周",
        january: "一月",
        february: "二月",
        march: "三月",
        quarter1: "第1季度",
        quarter2: "第2季度",
        quarter3: "第3季度",
        quarter4: "第4季度",
        history: "历史",
        withdraw_cash: "提取现金",
        download_report_function: "下载报告功能",
        withdrawal_success: "现金提取成功",
        expense_history: "支出历史",
        category: "类别",
        amount: "金额",
        description: "描述",
        enter_amount: "输入金额",
        select_reason: "选择原因",
        enter_additional_description: "输入额外描述",
        confirm: "确认",

        // Withdrawal reasons
        salary: "医生薪资",
        salary_increase: "医生额外薪资",
        utilities: "水电费",
        rent: "租金",
        supplies: "医疗用品采购",
        medicine: "药品采购",
        repairs: "维修工作",
        marketing: "市场营销费用",
        taxes: "税费",
        other_expenses: "其他费用",
        other: "其他",

        // Withdrawal descriptions
        salary_payment_description: "医生月薪支付",
        utilities_payment_description: "电费和水费支付",
        supplies_payment_description: "新医疗设备采购",
        medicine_payment_description: "药品采购",
        salary_increase_description: "Aziz Karimov医生的额外薪资",
        rent_payment_description: "月租支付",
        all_branches: "所有分支",

        // Inpatient Rooms
        inpatient_rooms: "住院病房",
        current_rooms: "当前病房",
        room_history: "病房历史",
        add_new_room: "添加新病房",
        edit_room: "编辑病房",
        confirm_delete_room: "您确定要删除这个病房吗？",
        room_number: "病房号",
        room_type: "病房类型",
        standard_room: "标准病房",
        premium_room: "高级病房",
        intensive_care: "重症监护",
        daily_rate: "日费率",
        available: "可用",
        occupied: "已占用",
        maintenance: "维护中",
        room: "病房",
        type: "类型",
        capacity: "容量",
        description: "描述",
        current_patients: "当前患者",
        no_patients_in_room: "此病房没有患者",
        assign_patient: "分配患者",
        assign_patient_to_room: "将患者分配到病房",
        admission_date: "入院日期",
        expected_discharge_date: "预计出院日���",
        expected_discharge: "预计出院",
        remaining_days: "剩余天数",
        discharge: "出院",
        confirm_discharge_patient: "您确定要让这位患者出院吗？",
        add_payment: "添加付款",
        add_payment_for: "为以下添加付款",
        payment_method: "付款方式",
        payment_date: "付款日期",
        total_payment: "总付款",
        room_occupancy_history: "病房占用历史",
        discharge_date: "出院日期",
        duration: "持续时间",
        days: "天",
        no_room_history: "没有病房历史",
        inpatient_rooms_statistics: "住院病房统计",
        total_rooms: "总病房数",
        available_rooms: "可用病房",
        occupied_rooms: "已占用病房",
        maintenance_rooms: "维护中病房",
        total_inpatients: "总住院患者",
        average_stay_duration: "平均住院时间",
        occupancy_rate: "占用率",
        total_revenue: "总收入",
        average_daily_revenue: "平均日收入",
        close: "关闭",
        search_rooms_patients: "搜索病房和患者...",
        all_rooms: "所有病房",
        select_nurse: "选择护士",
        morning_shift: "早班",
        evening_shift: "晚班",
        night_shift: "夜班",
        critical: "危重",
        recovering: "恢复中",
        active: "活跃",
    },
}

// Create language context
const LanguageContext = createContext()

// Language provider component
export const LanguageProvider = ({ children }) => {
    // Get browser language or use default
    const getBrowserLanguage = () => {
        if (typeof window !== "undefined") {
            const savedLanguage = localStorage.getItem("language")
            if (savedLanguage && languages[savedLanguage]) {
                return savedLanguage
            }

            const browserLang = navigator.language.split("-")[0]
            return languages[browserLang] ? browserLang : "en"
        }
        return "en"
    }

    const [language, setLanguage] = useState("en")

    useEffect(() => {
        setLanguage(getBrowserLanguage())
    }, [])

    // Change language function
    const changeLanguage = (lang) => {
        if (languages[lang]) {
            setLanguage(lang)
            if (typeof window !== "undefined") {
                localStorage.setItem("language", lang)
            }
        }
    }

    // Translate function
    const t = (key) => {
        if (!translations[language]) return key
        return translations[language][key] || key
    }

    return (
        <LanguageContext.Provider value={{ language, languages, changeLanguage, t }}>{children}</LanguageContext.Provider>
    )
}

// Custom hook to use language context
export const useLanguage = () => {
    const context = useContext(LanguageContext)
    if (!context) {
        throw new Error("useLanguage must be used within a LanguageProvider")
    }
    return context
}

export default LanguageContext;